Repository Nexmo/deved-platform, pull requests merged in 2020-11, with the labels that each got.

#229 Create Blog Post “meet-the-first-voyagers-crew-part-1”
  content/blog/en/meet-the-first-voyagers-crew-part-1.md
  static/content/blog/meet-the-first-voyagers-crew-part-1/blog_vonage-voyagers_1_1200x600.png
  static/content/blog/meet-the-first-voyagers-crew-part-1/image1.png
  static/content/blog/meet-the-first-voyagers-crew-part-1/image2.png
  static/content/blog/meet-the-first-voyagers-crew-part-1/image3.png
Labels: netlify-cms/pending_publish

#228 Update Blog Post “use-web-components-in-vue-2-and-3-composition-api-dr”
  content/blog/en/use-web-components-in-vue-2-and-3-composition-api-dr.md
  static/content/blog/use-web-components-in-vue-2-and-3-composition-api/codesandbox-server-control-panel.jpg
  static/content/blog/use-web-components-in-vue-2-and-3-composition-api/vue-warn.jpg
  static/content/blog/use-web-components-in-vue-2-and-3-composition-api/vue2-custom-elements-everywhere.jpg
Labels: netlify-cms/pending_publish

#231 Create Blog Post “receive-inbound-sms-with-go”
  content/blog/en/receive-inbound-sms-with-go.md
  static/content/blog/receive-inbound-sms-with-go/blog_go_sms_1200x600.png
Labels: netlify-cms/pending_publish

#244 Update Blog Post “using-apollo-to-query-graphql-from-node-js-dr”
  content/blog/en/using-apollo-to-query-graphql-from-node-js-dr.md
  static/content/blog/using-apollo-to-query-graphql-from-node-js/tb-project-created.png
Labels: netlify-cms/pending_publish

#237 Update Blog Post “send-and-receive-sms-messages-with-firebase-functions-dr”
  content/blog/en/send-and-receive-sms-messages-with-firebase-functions-dr.md
  static/content/blog/send-and-receive-sms-messages-with-firebase-functions/add-analytics.png
  static/content/blog/send-and-receive-sms-messages-with-firebase-functions/create-project.png
  static/content/blog/send-and-receive-sms-messages-with-firebase-functions/database-nexmo-object.png
  static/content/blog/send-and-receive-sms-messages-with-firebase-functions/name-project.png
  static/content/blog/send-and-receive-sms-messages-with-firebase-functions/update-billing.png
  static/content/blog/send-and-receive-sms-messages-with-firebase-functions/update-location.png
Labels: netlify-cms/pending_publish

#236 Update Blog Post “receiving-an-sms-with-php-dr”
  content/blog/en/receiving-an-sms-with-php-dr.md
Labels: netlify-cms/pending_publish

#234 Update Blog Post “receive-sms-messages-java-dr”
  content/blog/en/receive-sms-messages-java-dr.md
  static/content/blog/how-to-receive-sms-messages-with-java/diagram-receive.png
Labels: netlify-cms/pending_publish

#255 [skip ci] Hotfix Netlify CMS config
  static/admin/config.yml
Labels: 🐞 bug, 🚀 ready-to-go

#257 Create Blog Post “the-right-way-of-using-gradle-dynamic-dependencies”
  content/blog/en/the-right-way-of-using-gradle-dynamic-dependencies.md
  static/content/blog/the-right-way-of-using-gradle-dynamic-dependencies/blog_gradle-dynamic-dependencies_1200x600.png
Labels: netlify-cms/pending_publish

#254 Update Blog Post “create-a-simple-messaging-ui-with-bootstrap-dr”
  content/blog/en/create-a-simple-messaging-ui-with-bootstrap-dr.md
  static/content/blog/create-a-simple-messaging-ui-with-bootstrap/1.png
  static/content/blog/create-a-simple-messaging-ui-with-bootstrap/10.png
  static/content/blog/create-a-simple-messaging-ui-with-bootstrap/11.png
  static/content/blog/create-a-simple-messaging-ui-with-bootstrap/12.png
  static/content/blog/create-a-simple-messaging-ui-with-bootstrap/13.png
  static/content/blog/create-a-simple-messaging-ui-with-bootstrap/14.png
  static/content/blog/create-a-simple-messaging-ui-with-bootstrap/2.png
  static/content/blog/create-a-simple-messaging-ui-with-bootstrap/3.png
  static/content/blog/create-a-simple-messaging-ui-with-bootstrap/4.png
  static/content/blog/create-a-simple-messaging-ui-with-bootstrap/5.png
  static/content/blog/create-a-simple-messaging-ui-with-bootstrap/6.png
  static/content/blog/create-a-simple-messaging-ui-with-bootstrap/7.png
  static/content/blog/create-a-simple-messaging-ui-with-bootstrap/8.png
  static/content/blog/create-a-simple-messaging-ui-with-bootstrap/9.png
Labels: netlify-cms/pending_publish

#256 Create Blog Post “hacktoberfest-2020-the-roundup”
  content/blog/en/hacktoberfest-2020-the-roundup.md
  static/content/blog/hacktoberfest-2020-the-roundup/blog_writeup_hacktoberfest_2020_1200x600.png
  static/content/blog/hacktoberfest-2020-the-roundup/hacktoberfest_visualised.png
Labels: netlify-cms/pending_publish

#259 Update Blog Post “join-the-outsystems-vonage-linkit-2020-developer-challenge”
  content/blog/en/join-the-outsystems-vonage-linkit-2020-developer-challenge.md
Labels: netlify-cms/pending_publish

#261 Update Blog Post “12-bots-to-better-your-open-source-project”
  content/blog/en/12-bots-to-better-your-open-source-project.md
  static/content/blog/12-bots-to-better-your-open-source-project/apps-vs-actions.png
  static/content/blog/12-bots-to-better-your-open-source-project/labeler.png
  static/content/blog/12-bots-to-better-your-open-source-project/lint-action.png
  static/content/blog/12-bots-to-better-your-open-source-project/lock-threads.png
  static/content/blog/12-bots-to-better-your-open-source-project/no-response-test.png
  static/content/blog/12-bots-to-better-your-open-source-project/req-info.png
  static/content/blog/12-bots-to-better-your-open-source-project/size-limit.png
  static/content/blog/12-bots-to-better-your-open-source-project/stale.png
Labels: netlify-cms/pending_publish

#282 Add previews into Netlify CMS
  static/admin/config.yml
  static/admin/index.html
  static/admin/netlify-preview.css
Labels: 🧙‍♂️    enhancement

#281 Update Blog Post “how-to-add-two-factor-authentication-with-node-js-dr”
  content/blog/en/how-to-add-two-factor-authentication-with-node-js-dr.md
  static/content/blog/how-to-add-two-factor-authentication-with-node-js-and-koa-js/e53b88bf-b990-43c3-8efd-a5141145a96c_check.png
  static/content/blog/how-to-add-two-factor-authentication-with-node-js-and-koa-js/e53b88bf-b990-43c3-8efd-a5141145a96c_glitch.png
  static/content/blog/how-to-add-two-factor-authentication-with-node-js-and-koa-js/e53b88bf-b990-43c3-8efd-a5141145a96c_koa-server.png
  static/content/blog/how-to-add-two-factor-authentication-with-node-js-and-koa-js/e53b88bf-b990-43c3-8efd-a5141145a96c_landing.png
  static/content/blog/how-to-add-two-factor-authentication-with-node-js-and-koa-js/e53b88bf-b990-43c3-8efd-a5141145a96c_message.png
  static/content/blog/how-to-add-two-factor-authentication-with-node-js-and-koa-js/e53b88bf-b990-43c3-8efd-a5141145a96c_npm-init.png
Labels: netlify-cms/pending_publish

#277 Update Blog Post “record-a-call-in-ruby-with-vonage-voice-api-websockets”
  content/blog/en/record-a-call-in-ruby-with-vonage-voice-api-websockets.md
Labels: netlify-cms/pending_publish

#279 Update Blog Post “send-a-whatsapp-message-with-node-dr”
  content/blog/en/send-a-whatsapp-message-with-node-dr.md
  static/content/blog/how-to-send-a-whatsapp-message-with-node-js/whatsapp-whitelisting.jpeg
Labels: netlify-cms/pending_publish

#274 Update Blog Post “receive-inbound-sms-with-go”
  content/blog/en/receive-inbound-sms-with-go.md
Labels: netlify-cms/pending_publish

#275 Update Blog Post “streaming-calls-to-a-browser-with-voice-websockets-dr”
  content/blog/en/streaming-calls-to-a-browser-with-voice-websockets-dr.md
  static/content/blog/streaming-calls-to-a-browser-with-voice-websockets/audiosocket-arch.001.jpeg
  static/content/blog/streaming-calls-to-a-browser-with-voice-websockets/audiosocket-seq.002.jpeg
Labels: netlify-cms/pending_publish

#273 Update Blog Post “how-to-receive-an-sms-message-with-asp-net-core-mvc-and-signalr”
  content/blog/en/how-to-receive-an-sms-message-with-asp-net-core-mvc-and-signalr.md
  static/content/blog/how-to-receive-an-sms-message-with-asp-net-core-mvc-and-signalr/add_client_side.png
  static/content/blog/how-to-receive-an-sms-message-with-asp-net-core-mvc-and-signalr/displayed_messages.png
  static/content/blog/how-to-receive-an-sms-message-with-asp-net-core-mvc-and-signalr/iis_express_config.png
  static/content/blog/how-to-receive-an-sms-message-with-asp-net-core-mvc-and-signalr/ngrok-1.png
Labels: netlify-cms/pending_publish

#271 Update Blog Post “build-an-sms-dashboard-with-blazor-webassembly”
  content/blog/en/build-an-sms-dashboard-with-blazor-webassembly.md
  static/content/blog/build-an-sms-dashboard-with-blazor-webassembly/createblazorapp.png
  static/content/blog/build-an-sms-dashboard-with-blazor-webassembly/dashboard.png
  static/content/blog/build-an-sms-dashboard-with-blazor-webassembly/smsdashboardview.png
Labels: netlify-cms/pending_publish

#272 Update Blog Post “aws-cognito-verify-with-php”
  content/blog/en/aws-cognito-verify-with-php.md
Labels: netlify-cms/pending_publish

#269 Update Blog Post “create-websocket-server-java-api-dr”
  content/blog/en/create-websocket-server-java-api-dr.md
Labels: netlify-cms/pending_publish

#270 Update Blog Post “send-sms-messages-asp-net-mvc-framework-dr”
  content/blog/en/send-sms-messages-asp-net-mvc-framework-dr.md
Labels: netlify-cms/pending_publish

#265 Update Blog Post “connect-to-the-ethereum-blockchain-with-node-js-and-vonage-dr”
  content/blog/en/connect-to-the-ethereum-blockchain-with-node-js-and-vonage-dr.md
  static/content/blog/connect-to-the-ethereum-blockchain-with-node-js-and-vonage/s_7d49c4022d5c8ee1cd911307f43dbac8fc65f6a90161aeb6bd94a53118116bd3_1583727450885_screenshot-from-2020-03-09-05-16-57.png
  static/content/blog/connect-to-the-ethereum-blockchain-with-node-js-and-vonage/s_7d49c4022d5c8ee1cd911307f43dbac8fc65f6a90161aeb6bd94a53118116bd3_1583741399346_screenshot-from-2020-03-09-09-07-18.png
  static/content/blog/connect-to-the-ethereum-blockchain-with-node-js-and-vonage/vonage_apis_dashboard.png
Labels: netlify-cms/pending_publish

#264 Update Blog Post “add-sms-verification-in-a-react-native-app-using-node-js-and-express-dr”
  content/blog/en/add-sms-verification-in-a-react-native-app-using-node-js-and-express-dr.md
  static/content/blog/add-sms-verification-in-a-react-native-app-using-node-js-and-express/my_numbers_vonage.png
  static/content/blog/add-sms-verification-in-a-react-native-app-using-node-js-and-express/no_sms_demo.gif
  static/content/blog/add-sms-verification-in-a-react-native-app-using-node-js-and-express/sms_demo.gif
  static/content/blog/add-sms-verification-in-a-react-native-app-using-node-js-and-express/vonage_keys.png
Labels: netlify-cms/pending_publish

#262 Update Blog Post “create-a-basic-video-chat-app-with-asp-net-and-angular-dr”
  content/blog/en/create-a-basic-video-chat-app-with-asp-net-and-angular-dr.md
  static/content/blog/create-a-basic-video-chat-app-with-asp-net-and-angular/joinview.png
  static/content/blog/create-a-basic-video-chat-app-with-asp-net-and-angular/videoview.png
Labels: netlify-cms/pending_publish

#263 Update Blog Post “migrating-react-components-to-vue-js-dr”
  content/blog/en/migrating-react-components-to-vue-js-dr.md
  static/content/blog/migrating-react-components-to-vue-js/component-image.png
Labels: netlify-cms/pending_publish

#296 Create Authors “filippos-kyprianou”
  content/authors/filippos-kyprianou.json
  static/content/images/t02nnhd8s-u01bfpcfu6m-60e718bd0e6e-512.png
Labels: netlify-cms/pending_publish

#297 Create Blog Post “filippos-kyprianou-joins-the-vonage-community-team”
  content/blog/en/filippos-kyprianou-joins-the-vonage-community-team.md
  static/content/blog/filippos-kyprianou-joins-the-vonage-community-team/filippos-kyprianou.png
Labels: netlify-cms/pending_publish

#311 Update Blog Post “serverless-python-with-aws-lambda-dr”
  content/blog/en/serverless-python-with-aws-lambda-dr.md
  static/content/blog/serverless-python-with-aws-lambda/45f61f57-3077-4f6a-8493-52f12a050680.png
  static/content/blog/serverless-python-with-aws-lambda/aws_console_compute_lambda.png
  static/content/blog/serverless-python-with-aws-lambda/aws_console_name_function.png
  static/content/blog/serverless-python-with-aws-lambda/aws_lambda_python_project_creation.png
  static/content/blog/serverless-python-with-aws-lambda/b4a21e49-7050-4683-933e-8b22bf3e5c13.png
  static/content/blog/serverless-python-with-aws-lambda/browser_api_gateway_launch.png
  static/content/blog/serverless-python-with-aws-lambda/configure_test_events.png
  static/content/blog/serverless-python-with-aws-lambda/lambda_function_create_test.png
  static/content/blog/serverless-python-with-aws-lambda/lambda_test_results.png
Labels: netlify-cms/pending_publish

#308 Update Blog Post “opentok-react-components-dr”
  content/blog/en/opentok-react-components-dr.md
  static/content/blog/create-custom-video-chat-with-react-components-and-vonage/newproject.png
  static/content/blog/create-custom-video-chat-with-react-components-and-vonage/npmstart.png
  static/content/blog/create-custom-video-chat-with-react-components-and-vonage/sessionid.png
  static/content/blog/create-custom-video-chat-with-react-components-and-vonage/tweet.png
Labels: netlify-cms/pending_publish

#309 Update Blog Post “using-amazon-sqs-for-queuing-messages-using-aws-lambda-and-python”
  content/blog/en/using-amazon-sqs-for-queuing-messages-using-aws-lambda-and-python.md
Labels: netlify-cms/pending_publish

#306 Update Blog Post “real-time-human-detection-with-opencv-and-vonage-sms-api-dr”
  content/blog/en/real-time-human-detection-with-opencv-and-vonage-sms-api-dr.md
  static/content/blog/real-time-human-detection-with-opencv-and-vonage-sms-api/pasted-image-0.png
Labels: netlify-cms/pending_publish

#307 Update Blog Post “make-outbound-text-speech-phone-call-node-js-dr”
  content/blog/en/make-outbound-text-speech-phone-call-node-js-dr.md
  static/content/blog/how-to-make-an-outbound-text-to-speech-phone-call-with-node-js/voice-make-call-diagram.png
Labels: netlify-cms/pending_publish

#304 Update Blog Post “build-chat-app-angular-material-stitch-javascript-dr”
  content/blog/en/build-chat-app-angular-material-stitch-javascript-dr.md
  static/content/blog/build-a-chat-application-with-angular-material-and-vonage/end-game.gif
Labels: netlify-cms/pending_publish

#305 Update Blog Post “nexmo-messages-api-integration-with-marketo-dr”
  content/blog/en/nexmo-messages-api-integration-with-marketo-dr.md
  static/content/blog/send-whatsapp-and-sms-messages-from-marketo/admin_console.png
  static/content/blog/send-whatsapp-and-sms-messages-from-marketo/edit_webhook_sms.png
  static/content/blog/send-whatsapp-and-sms-messages-from-marketo/edit_webhook_wa.png
  static/content/blog/send-whatsapp-and-sms-messages-from-marketo/marketing_activities.png
  static/content/blog/send-whatsapp-and-sms-messages-from-marketo/new_program.png
  static/content/blog/send-whatsapp-and-sms-messages-from-marketo/smart_list.png
  static/content/blog/send-whatsapp-and-sms-messages-from-marketo/webhooks_select.png
Labels: netlify-cms/pending_publish

#301 Update Blog Post “home-surveillance-system-with-node-and-a-raspberry-pi”
  content/blog/en/home-surveillance-system-with-node-and-a-raspberry-pi.md
  static/content/blog/home-surveillance-system-with-node-and-a-raspberry-pi/gpio-pinout-diagram-2.png
  static/content/blog/home-surveillance-system-with-node-and-a-raspberry-pi/raspberry-pi-camera-ribbon.jpeg
  static/content/blog/home-surveillance-system-with-node-and-a-raspberry-pi/raspberry-pi.jpeg
  static/content/blog/home-surveillance-system-with-node-and-a-raspberry-pi/raspi-config.png
  static/content/blog/home-surveillance-system-with-node-and-a-raspberry-pi/sensor-wiring-pt1.jpeg
  static/content/blog/home-surveillance-system-with-node-and-a-raspberry-pi/sensor-wiring-pt2.jpeg
Labels: netlify-cms/pending_publish

#299 Update Blog Post “aws-lambda-with-php-using-bref-and-serverless-framework-dr”
  content/blog/en/aws-lambda-with-php-using-bref-and-serverless-framework-dr.md
  static/content/blog/aws-lambda-with-php-using-bref-and-serverless-framework/aws_console_compute_lambda.png
  static/content/blog/aws-lambda-with-php-using-bref-and-serverless-framework/configure_test_events.png
  static/content/blog/aws-lambda-with-php-using-bref-and-serverless-framework/lambda_function_create_test.png
  static/content/blog/aws-lambda-with-php-using-bref-and-serverless-framework/lambda_test_results.png
  static/content/blog/aws-lambda-with-php-using-bref-and-serverless-framework/serverless_lambda_function_execution.png
Labels: netlify-cms/pending_publish

#300 Update Blog Post “sending-sms-messages-with-php-dr”
  content/blog/en/sending-sms-messages-with-php-dr.md
Labels: netlify-cms/pending_publish

#293 Update Blog Post “real-time-face-detection-in-net-with-opentok-and-opencv-dr”
  content/blog/en/real-time-face-detection-in-net-with-opentok-and-opencv-dr.md
  static/content/blog/real-time-face-detection-in-net-with-opencv-and-video/haarfeatureshapes.png
  static/content/blog/real-time-face-detection-in-net-with-opencv-and-video/haarfeaturesoverfaces.jpg
  static/content/blog/real-time-face-detection-in-net-with-opencv-and-video/joinwithplayground.gif
  static/content/blog/real-time-face-detection-in-net-with-opencv-and-video/post_build_event.png
  static/content/blog/real-time-face-detection-in-net-with-opencv-and-video/project_upgrade.png
  static/content/blog/real-time-face-detection-in-net-with-opencv-and-video/with_blue_filter.png
  static/content/blog/real-time-face-detection-in-net-with-opencv-and-video/with_face_detection.png
  static/content/blog/real-time-face-detection-in-net-with-opencv-and-video/without_filter.png
Labels: netlify-cms/pending_publish

#295 Update Blog Post “phone-call-web-browser-nexmo-in-app-voice-vue-js-dr”
  content/blog/en/phone-call-web-browser-nexmo-in-app-voice-vue-js-dr.md
  static/content/blog/making-phone-calls-from-a-web-browser-with-vue-js-and-vonage/call-from-browser-ui.png
  static/content/blog/making-phone-calls-from-a-web-browser-with-vue-js-and-vonage/component-diagram.png
  static/content/blog/making-phone-calls-from-a-web-browser-with-vue-js-and-vonage/conversation-not-found.png
  static/content/blog/making-phone-calls-from-a-web-browser-with-vue-js-and-vonage/jwt-in-browser.png
  static/content/blog/making-phone-calls-from-a-web-browser-with-vue-js-and-vonage/ngrok.png
  static/content/blog/making-phone-calls-from-a-web-browser-with-vue-js-and-vonage/userjwt-null.png
  static/content/blog/making-phone-calls-from-a-web-browser-with-vue-js-and-vonage/userjwt.png
  static/content/blog/making-phone-calls-from-a-web-browser-with-vue-js-and-vonage/vue-tel-input.gif
  static/content/blog/making-phone-calls-from-a-web-browser-with-vue-js-and-vonage/working-app.png
Labels: netlify-cms/pending_publish

#292 Update Blog Post “automated-message-migration-from-aws-sqs-to-dynamodb”
  content/blog/en/automated-message-migration-from-aws-sqs-to-dynamodb.md
Labels: netlify-cms/pending_publish

#288 Update Blog Post “send-sms-messages-python-flask-dr”
  content/blog/en/send-sms-messages-python-flask-dr.md
  static/content/blog/how-to-send-sms-messages-with-python-flask-and-vonage/sms_received.png
  static/content/blog/how-to-send-sms-messages-with-python-flask-and-vonage/smsweb_send.png
Labels: netlify-cms/pending_publish

#290 Update Blog Post “build-a-conference-call-with-python-dr”
  content/blog/en/build-a-conference-call-with-python-dr.md
Labels: netlify-cms/pending_publish

#285 Update Blog Post “send-sms-messages-with-java-dr”
  content/blog/en/send-sms-messages-with-java-dr.md
  static/content/blog/how-to-send-sms-messages-with-java/empty-web.png
  static/content/blog/how-to-send-sms-messages-with-java/github-mark-64px.png
  static/content/blog/how-to-send-sms-messages-with-java/postman-request.png
Labels: netlify-cms/pending_publish

#287 Update Blog Post “send-sms-ruby-on-rails-dr”
  content/blog/en/send-sms-ruby-on-rails-dr.md
  static/content/blog/how-to-send-sms-messages-with-ruby-on-rails/android.png
  static/content/blog/how-to-send-sms-messages-with-ruby-on-rails/send-ui.png
Labels: netlify-cms/pending_publish

#284 Update Blog Post “how-to-play-an-audio-stream-into-a-call-with-python-dr”
  content/blog/en/how-to-play-an-audio-stream-into-a-call-with-python-dr.md
Labels: netlify-cms/pending_publish

#268 Update Blog Post “chat-pagination-with-infinite-scrolling-dr”
  content/blog/en/chat-pagination-with-infinite-scrolling-dr.md
  static/content/blog/chat-pagination-with-infinite-scrolling/nexmo-chat-alert-scrolling-to-top.png
  static/content/blog/chat-pagination-with-infinite-scrolling/nexmo-chat-infinite-scrolling-to-the-top.png
  static/content/blog/chat-pagination-with-infinite-scrolling/nexmo-chat-simple-messaging-ui.png
Labels: netlify-cms/pending_publish

#283 Update Blog Post “real-time-call-transcription-ibm-watson-python-dr”
  content/blog/en/real-time-call-transcription-ibm-watson-python-dr.md
  static/content/blog/real-time-call-transcription-using-ibm-watson-and-python/watson_flow.png
Labels: netlify-cms/pending_publish

#267 Update Blog Post “stripe-sms-laravel-dotun”
  content/blog/en/stripe-sms-laravel-dotun.md
  static/content/blog/stripe-sms-notifications-using-laravel-and-nexmo/buy-a-number.png
  static/content/blog/stripe-sms-notifications-using-laravel-and-nexmo/ngrok.png
  static/content/blog/stripe-sms-notifications-using-laravel-and-nexmo/sms-600x237.png
  static/content/blog/stripe-sms-notifications-using-laravel-and-nexmo/stripe-768x737.png
  static/content/blog/stripe-sms-notifications-using-laravel/ngrok.png
  static/content/blog/stripe-sms-notifications-using-laravel/sms-600x237.png
  static/content/blog/stripe-sms-notifications-using-laravel/stripe.png
Labels: netlify-cms/pending_publish

#322 Update Authors “filippos-kyprianou”
  content/authors/filippos-kyprianou.json
Labels: netlify-cms/pending_publish

#321 Update Blog Post “filippos-kyprianou-joins-the-vonage-community-team”
  content/blog/en/filippos-kyprianou-joins-the-vonage-community-team.md
Labels: netlify-cms/draft

#315 Create Blog Post “meet-the-first-voyagers-crew-part-2”
  content/blog/en/meet-the-first-voyagers-crew-part-2.md
  static/content/blog/meet-the-first-voyagers-crew-part-2/blog_vonage-voyagers_3_1200x600.png
  static/content/blog/meet-the-first-voyagers-crew-part-2/henry.png
  static/content/blog/meet-the-first-voyagers-crew-part-2/joe.png
  static/content/blog/meet-the-first-voyagers-crew-part-2/michael.png
Labels: netlify-cms/pending_publish

#341 Update Blog Post “how-to-send-an-sms-with-ionic-dr”
  content/blog/en/how-to-send-an-sms-with-ionic-dr.md
Labels: netlify-cms/pending_publish

#340 Update Blog Post “sending-sms-from-python-with-google-cloud-functions-dr”
  content/blog/en/sending-sms-from-python-with-google-cloud-functions-dr.md
  static/content/blog/sending-sms-from-python-with-google-cloud-functions/advanced-settings.png
  static/content/blog/sending-sms-from-python-with-google-cloud-functions/creating-function.png
Labels: netlify-cms/pending_publish

#338 Update Blog Post “how-to-use-azure-functions-with-python-dr”
  content/blog/en/how-to-use-azure-functions-with-python-dr.md
Labels: netlify-cms/pending_publish

#339 Update Blog Post “how-to-send-an-sms-with-asp-net-core-mvc”
  content/blog/en/how-to-send-an-sms-with-asp-net-core-mvc.md
Labels: netlify-cms/pending_publish

#336 Update Blog Post “send-whatsapp-messages-with-laravel-dr”
  content/blog/en/send-whatsapp-messages-with-laravel-dr.md
  static/content/blog/how-to-send-whatsapp-messages-with-laravel/laravel-chat.png
  static/content/blog/how-to-send-whatsapp-messages-with-laravel/laravel.png
  static/content/blog/how-to-send-whatsapp-messages-with-laravel/ngrok-1.png
  static/content/blog/how-to-send-whatsapp-messages-with-laravel/sandbox-qr.png
  static/content/blog/how-to-send-whatsapp-messages-with-laravel/sandbox-webhooks.png
Labels: netlify-cms/pending_publish

#337 Update Blog Post “translate-a-phone-call-with-blazor-signalr-and-azure-dr”
  content/blog/en/translate-a-phone-call-with-blazor-signalr-and-azure-dr.md
  static/content/blog/translate-a-phone-call-with-blazor-signalr-and-azure/ngroksettings-1.png
Labels: netlify-cms/pending_publish

#333 Update Blog Post “how-make-receive-phone-calls-with-nuxt-js-dr”
  content/blog/en/how-make-receive-phone-calls-with-nuxt-js-dr.md
Labels: netlify-cms/pending_publish

#334 Update Blog Post “web-components-tools-a-comparison”
  content/blog/en/web-components-tools-a-comparison.md
Labels: netlify-cms/pending_publish

#332 Update Blog Post “using-private-keys-in-environment-variables”
  content/blog/en/using-private-keys-in-environment-variables.md
Labels: netlify-cms/pending_publish

#330 Update Blog Post “send-sms-messages-node-red-dr”
  content/blog/en/send-sms-messages-node-red-dr.md
  static/content/blog/how-to-send-sms-messages-with-node-red/delivery-receipt-endpoint-url.png
  static/content/blog/how-to-send-sms-messages-with-node-red/delivery-receipt-flow.gif
  static/content/blog/how-to-send-sms-messages-with-node-red/delivery-receipt-in-debug.png
  static/content/blog/how-to-send-sms-messages-with-node-red/install-nexmo-nodered.gif
  static/content/blog/how-to-send-sms-messages-with-node-red/ngrok-1880.png
  static/content/blog/how-to-send-sms-messages-with-node-red/send-sms-flow.gif
Labels: netlify-cms/pending_publish

#331 Update Blog Post “sms-notifications-browser-with-angular-node-ably-dr”
  content/blog/en/sms-notifications-browser-with-angular-node-ably-dr.md
  static/content/blog/how-to-show-sms-notifications-in-the-browser-with-angular-node-js-and-ably/boilerplate-app.png
  static/content/blog/how-to-show-sms-notifications-in-the-browser-with-angular-node-js-and-ably/demo.gif
  static/content/blog/how-to-show-sms-notifications-in-the-browser-with-angular-node-js-and-ably/generated-files.png
  static/content/blog/how-to-show-sms-notifications-in-the-browser-with-angular-node-js-and-ably/ng-serve.png
  static/content/blog/how-to-show-sms-notifications-in-the-browser-with-angular-node-js-and-ably/ngrok-requests.png
  static/content/blog/how-to-show-sms-notifications-in-the-browser-with-angular-node-js-and-ably/set-webhook.png
  static/content/blog/how-to-show-sms-notifications-in-the-browser-with-angular-node-js-and-ably/start-ngrok.png
Labels: netlify-cms/pending_publish

#325 Update Blog Post “implement-two-factor-authentication-2fa-web-apps-node-js-dr”
  content/blog/en/implement-two-factor-authentication-2fa-web-apps-node-js-dr.md
  static/content/blog/how-to-add-two-factor-authentication-2fa-to-your-node-js-web-apps/screenshot.gif
  static/content/blog/how-to-add-two-factor-authentication-2fa-to-your-node-js-web-apps/simple-form.png
  static/content/blog/how-to-add-two-factor-authentication-2fa-to-your-node-js-web-apps/verify-pin.png
Labels: netlify-cms/pending_publish

#329 Update Blog Post “integrating-the-conversation-api-with-wechat-dr”
  content/blog/en/integrating-the-conversation-api-with-wechat-dr.md
  static/content/blog/integrating-the-conversation-api-with-wechat/wechat1.png
  static/content/blog/integrating-the-conversation-api-with-wechat/wechat2.png
  static/content/blog/integrating-the-conversation-api-with-wechat/wechat3.png
Labels: netlify-cms/pending_publish

#323 Update Blog Post “creating-a-web-component-with-open-wc”
  content/blog/en/creating-a-web-component-with-open-wc.md
  static/content/blog/creating-a-web-component-with-open-wc/adddigit.gif
  static/content/blog/creating-a-web-component-with-open-wc/npm-i-material-720.gif
  static/content/blog/creating-a-web-component-with-open-wc/npm-init-open-wc-720.gif
  static/content/blog/creating-a-web-component-with-open-wc/npm-init-scope-your-npm-username-720.gif
  static/content/blog/creating-a-web-component-with-open-wc/npm-publish-access-public-720.gif
Labels: netlify-cms/pending_publish

#351 Create Authors “cristiano-betta”
  content/authors/cristiano-betta.json
  static/content/images/cbetta.png
Labels: netlify-cms/pending_publish

#328 Create Authors “roybenshushanfranssiswanto”
  content/authors/roybenshushanfranssiswanto.json
  static/content/images/screen-shot-2019-11-01-at-11.24.03-am.png
Labels: netlify-cms/pending_publish

#352 Create Blog Post “audit-phone-calls-with-event-sourcing-in-net”
  content/blog/en/audit-phone-calls-with-event-sourcing-in-net.md
  static/content/blog/audit-phone-calls-with-event-sourcing-in-net/image1.png
  static/content/blog/audit-phone-calls-with-event-sourcing-in-net/image2.png
  static/content/blog/audit-phone-calls-with-event-sourcing-in-net/image3.png
Labels: netlify-cms/pending_publish

#358 Create Blog Post “how-to-make-phone-calls-with-swiftui”
  content/blog/en/how-to-make-phone-calls-with-swiftui.md
  static/content/blog/how-to-make-phone-calls-with-swiftui/blog_swiftui_phone-call_1200x600.png
  static/content/blog/how-to-make-phone-calls-with-swiftui/call.gif
  static/content/blog/how-to-make-phone-calls-with-swiftui/ngrok.png
  static/content/blog/how-to-make-phone-calls-with-swiftui/projectdiagram.jpg
  static/content/blog/how-to-make-phone-calls-with-swiftui/xcodeproject.png
Labels: netlify-cms/pending_publish

#362 Update Blog Post “audit-phone-calls-with-event-sourcing-in-net”
  content/blog/en/audit-phone-calls-with-event-sourcing-in-net.md
  static/content/blog/audit-phone-calls-with-event-sourcing-in-net/blog_asp-net_callauditing_1200x600.png
  static/content/blog/audit-phone-calls-with-event-sourcing-in-net/blog_asp-net_voiceapi_1200x600.png
Labels: netlify-cms/pending_publish

#366 feat(i18n): better 404 handling for missing translations
  components/Errors/ErrorI18N.vue
  layouts/error.vue
Labels: 🧙‍♂️  enhancement

#368 Update Blog Post “receiving-an-sms-with-php-dr”
  content/blog/en/receiving-an-sms-with-php-dr.md
Labels: netlify-cms/pending_publish

#364 Update Blog Post “how-to-build-a-dashboard-of-live-conversations-with-flask-and-react-dr”
  content/blog/en/how-to-build-a-dashboard-of-live-conversations-with-flask-and-react-dr.md
  static/content/blog/how-to-build-a-dashboard-of-live-conversations-with-flask-and-react/5d894f3a32766539224729.gif
  static/content/blog/how-to-build-a-dashboard-of-live-conversations-with-flask-and-react/components.png
  static/content/blog/how-to-build-a-dashboard-of-live-conversations-with-flask-and-react/flowofapp.png
Labels: netlify-cms/pending_publish

#367 Update Blog Post “text-to-speech-voice-calls-with-php-dr”
  content/blog/en/text-to-speech-voice-calls-with-php-dr.md
Labels: netlify-cms/pending_publish

#363 Update Blog Post “how-send-receive-sms-messages-with-node-js-azure-functions-dr”
  content/blog/en/how-send-receive-sms-messages-with-node-js-azure-functions-dr.md
  static/content/blog/how-to-send-and-receive-sms-messages-with-node-js-and-azure-functions/add-env-variable.gif
  static/content/blog/how-to-send-and-receive-sms-messages-with-node-js-and-azure-functions/buy-number.gif
  static/content/blog/how-to-send-and-receive-sms-messages-with-node-js-and-azure-functions/create-azure-function.gif
  static/content/blog/how-to-send-and-receive-sms-messages-with-node-js-and-azure-functions/deploy-function.gif
  static/content/blog/how-to-send-and-receive-sms-messages-with-node-js-and-azure-functions/function-quickstart.gif
  static/content/blog/how-to-send-and-receive-sms-messages-with-node-js-and-azure-functions/function-template.gif
  static/content/blog/how-to-send-and-receive-sms-messages-with-node-js-and-azure-functions/set-inbound-webhook.gif
  static/content/blog/how-to-send-and-receive-sms-messages-with-node-js-and-azure-functions/sms-emoji.jpg
Labels: netlify-cms/pending_publish

#350 Update Blog Post “respect-api-rate-limits-with-a-backoff-dr”
  content/blog/en/respect-api-rate-limits-with-a-backoff-dr.md
  static/content/blog/respect-api-rate-limits-with-a-backoff/image1.png
  static/content/blog/respect-api-rate-limits-with-a-backoff/image2.png
  static/content/blog/respect-api-rate-limits-with-a-backoff/image3.gif
  static/content/blog/respect-api-rate-limits-with-a-backoff/image4.png
Labels: netlify-cms/pending_publish

#361 Create Blog Post “ban-the-trolls-adding-moderation-to-the-video-api”
  content/blog/en/ban-the-trolls-adding-moderation-to-the-video-api.md
Labels: netlify-cms/pending_publish

#349 Update Blog Post “2-factor-authentication-sms-voice-django-dr”
  content/blog/en/2-factor-authentication-sms-voice-django-dr.md
  static/content/blog/add-two-factor-authentication-to-your-django-app-with-nexmo/screen.gif
  static/content/blog/add-two-factor-authentication-to-your-django-app-with-nexmo/screen1.png
  static/content/blog/add-two-factor-authentication-to-your-django-app-with-nexmo/screen2.png
  static/content/blog/add-two-factor-authentication-to-your-django-app-with-nexmo/screen3.png
Labels: netlify-cms/pending_publish

#370 Update Blog Post “ban-the-trolls-adding-moderation-to-the-video-api”
  content/blog/en/ban-the-trolls-adding-moderation-to-the-video-api.md
  static/content/blog/ban-the-trolls-adding-moderation-to-the-video-api/blog_video-api_moderation_1200x600.png
Labels: netlify-cms/pending_publish

#371 Update Blog Post “ban-the-trolls-adding-moderation-to-the-video-api”
  content/blog/en/ban-the-trolls-adding-moderation-to-the-video-api.md
Labels: netlify-cms/pending_publish

#377 Create Authors “oluwatobi-okewole”
  content/authors/oluwatobi-okewole.json
  static/content/images/unnamed.jpg
Labels: netlify-cms/pending_publish

#376 Create Blog Post “implement-multi-factor-authentication-in-go-with-verify”
  content/blog/en/implement-multi-factor-authentication-in-go-with-verify.md
  static/content/blog/implement-multi-factor-authentication-in-go-with-verify/blog_go_verify2_1200x600.png
  static/content/blog/implement-multi-factor-authentication-in-go-with-verify/image1.png
  static/content/blog/implement-multi-factor-authentication-in-go-with-verify/image2.png
  static/content/blog/implement-multi-factor-authentication-in-go-with-verify/image3.png
Labels: netlify-cms/pending_publish

#382 Create Blog Post “meet-the-first-voyagers-crew-part-3”
  content/blog/en/meet-the-first-voyagers-crew-part-3.md
  static/content/blog/meet-the-first-voyagers-crew-part-3/blog_vonage-voyagers_4_1200x600.png
  static/content/blog/meet-the-first-voyagers-crew-part-3/hector.png
  static/content/blog/meet-the-first-voyagers-crew-part-3/mary-jo.png
  static/content/blog/meet-the-first-voyagers-crew-part-3/matthew-g.png
Labels: netlify-cms/pending_publish

#384 Update Authors “myrsini”
  content/authors/myrsini.json
Labels: netlify-cms/pending_publish

#385 Create Authors “yolanda-mcfadden”
  content/authors/yolanda-mcfadden.json
  static/content/images/yolanda-mcfadden-hris-analyst-2-.jpg
Labels: netlify-cms/pending_publish

#387 Update Blog Post “receiving-an-sms-with-php-dr”
  content/blog/en/receiving-an-sms-with-php-dr.md
Labels: netlify-cms/pending_publish

#386 Create Blog Post “send-sms-alerts-with-zapier-greenhouse-and-trello”
  content/blog/en/send-sms-alerts-with-zapier-greenhouse-and-trello.md
  static/content/blog/send-sms-alerts-with-zapier-greenhouse-and-trello/image1.png
  static/content/blog/send-sms-alerts-with-zapier-greenhouse-and-trello/image10.png
  static/content/blog/send-sms-alerts-with-zapier-greenhouse-and-trello/image11.png
  static/content/blog/send-sms-alerts-with-zapier-greenhouse-and-trello/image13.png
  static/content/blog/send-sms-alerts-with-zapier-greenhouse-and-trello/image14.png
  static/content/blog/send-sms-alerts-with-zapier-greenhouse-and-trello/image15.png
  static/content/blog/send-sms-alerts-with-zapier-greenhouse-and-trello/image2.png
  static/content/blog/send-sms-alerts-with-zapier-greenhouse-and-trello/image3.png
  static/content/blog/send-sms-alerts-with-zapier-greenhouse-and-trello/image4.png
  static/content/blog/send-sms-alerts-with-zapier-greenhouse-and-trello/image5.png
  static/content/blog/send-sms-alerts-with-zapier-greenhouse-and-trello/image6.png
  static/content/blog/send-sms-alerts-with-zapier-greenhouse-and-trello/image7.png
  static/content/blog/send-sms-alerts-with-zapier-greenhouse-and-trello/image8.png
  static/content/blog/send-sms-alerts-with-zapier-greenhouse-and-trello/zapier_recruitment1200x600.png
Labels: netlify-cms/pending_publish

#389 Update Authors “lukeoliff”
  content/authors/lukeoliff.json
Labels: netlify-cms/pending_publish

#388 Create Blog Post “receive-sms-delivery-receipts-with-go”
  content/blog/en/receive-sms-delivery-receipts-with-go.md
  static/content/blog/receive-sms-delivery-receipts-with-go/delivery-receipt-settings.png
  static/content/blog/receive-sms-delivery-receipts-with-go/sms-receipts_golang_1200x600.png
Labels: netlify-cms/pending_publish

#391 Update Blog Post “local-development-nexmo-ngrok-tunnel-dr”
  content/blog/en/local-development-nexmo-ngrok-tunnel-dr.md
Labels: netlify-cms/pending_publish

#390 Update Blog Post “best-practices-for-multi-party-video-conferencing-with-the-vonage-video-api-dr”
  content/blog/en/best-practices-for-multi-party-video-conferencing-with-the-vonage-video-api-dr.md
Labels: netlify-cms/pending_publish

#310 Update Blog Post “create-websocket-server-spring-boot-dr”
  content/blog/en/create-websocket-server-spring-boot-dr.md
Labels: netlify-cms/pending_publish

#398 Create Authors “aboze-brain-john”
  content/authors/aboze-brain-john.json
  static/content/images/profile-picture.jpg
Labels: netlify-cms/pending_publish

#402 Create Blog Post “sms-spam-detection-with-machine-learning-in-python”
  content/blog/en/sms-spam-detection-with-machine-learning-in-python.md
  static/content/blog/sms-spam-detection-with-machine-learning-in-python/image1.png
  static/content/blog/sms-spam-detection-with-machine-learning-in-python/image10.png
  static/content/blog/sms-spam-detection-with-machine-learning-in-python/image11.png
  static/content/blog/sms-spam-detection-with-machine-learning-in-python/image12.png
  static/content/blog/sms-spam-detection-with-machine-learning-in-python/image13.png
  static/content/blog/sms-spam-detection-with-machine-learning-in-python/image14.png
  static/content/blog/sms-spam-detection-with-machine-learning-in-python/image15.png
  static/content/blog/sms-spam-detection-with-machine-learning-in-python/image16.png
  static/content/blog/sms-spam-detection-with-machine-learning-in-python/image17.png
  static/content/blog/sms-spam-detection-with-machine-learning-in-python/image18.png
  static/content/blog/sms-spam-detection-with-machine-learning-in-python/image19.png
  static/content/blog/sms-spam-detection-with-machine-learning-in-python/image2.png
  static/content/blog/sms-spam-detection-with-machine-learning-in-python/image20.png
  static/content/blog/sms-spam-detection-with-machine-learning-in-python/image3.png
  static/content/blog/sms-spam-detection-with-machine-learning-in-python/image4.png
  static/content/blog/sms-spam-detection-with-machine-learning-in-python/image5.png
  static/content/blog/sms-spam-detection-with-machine-learning-in-python/image6.png
  static/content/blog/sms-spam-detection-with-machine-learning-in-python/image7.png
  static/content/blog/sms-spam-detection-with-machine-learning-in-python/image8.png
  static/content/blog/sms-spam-detection-with-machine-learning-in-python/image9.png
  static/content/blog/sms-spam-detection-with-machine-learning-in-python/python_flash_ml-sms_spam1200x600.png
Labels: netlify-cms/pending_publish

#403 Update Blog Post “sms-spam-detection-with-machine-learning-in-python”
  content/blog/en/sms-spam-detection-with-machine-learning-in-python.md
Labels: netlify-cms/pending_publish

#404 Update Blog Post “sms-spam-detection-with-machine-learning-in-python”
  content/blog/en/sms-spam-detection-with-machine-learning-in-python.md
Labels: netlify-cms/pending_publish

#405 Update Blog Post “sms-spam-detection-with-machine-learning-in-python”
  content/blog/en/sms-spam-detection-with-machine-learning-in-python.md
Labels: netlify-cms/pending_publish

#400 Create Blog Post “voice-api-speech-recognition-now-in-general-availability”
  content/blog/en/voice-api-speech-recognition-now-in-general-availability.md
  static/content/blog/voice-api-speech-recognition-now-in-general-availability/blog_speech-recognition_1120_1200x600.png
Labels: netlify-cms/pending_publish

#409 Update Authors “victorshisterov”
  content/authors/victorshisterov.json
  static/content/images/10144418.jpeg
Labels: netlify-cms/pending_publish

#393 Update Blog Post “5-ways-to-make-http-requests-in-node-js-2020-edition”
  content/blog/en/5-ways-to-make-http-requests-in-node-js-2020-edition.md
Labels: netlify-cms/pending_publish

#394 Update Blog Post “build-a-video-conference-app-with-react-native-and-vonage-video-api”
  content/blog/en/build-a-video-conference-app-with-react-native-and-vonage-video-api.md
  static/content/blog/build-a-video-conference-app-with-react-native-and-vonage-video-api/multiparty-mockup.png
  static/content/blog/build-a-video-conference-app-with-react-native-and-vonage-video-api/opentok-create-account.png
Labels: netlify-cms/pending_publish

#395 Update Blog Post “how-to-add-two-factor-authentication-with-node-js-and-express”
  content/blog/en/how-to-add-two-factor-authentication-with-node-js-and-express.md
  static/content/blog/how-to-add-two-factor-authentication-with-node-js-and-express/message.png
  static/content/blog/how-to-add-two-factor-authentication-with-node-js-and-express/overview.png
  static/content/blog/how-to-add-two-factor-authentication-with-node-js-and-express/request-id.png
Labels: netlify-cms/pending_publish

#396 Update Blog Post “real-time-human-detection-with-opencv-and-vonage-sms-api-dr”
  content/blog/en/real-time-human-detection-with-opencv-and-vonage-sms-api-dr.md
Labels: netlify-cms/pending_publish

#397 Update Blog Post “receive-an-sms-with-python-dr”
  content/blog/en/receive-an-sms-with-python-dr.md
Labels: netlify-cms/pending_publish

#399 Update Blog Post “how-to-send-a-facebook-messenger-message-with-node-js”
  content/blog/en/how-to-send-a-facebook-messenger-message-with-node-js.md
  static/content/blog/how-to-send-a-facebook-messenger-message-with-node-js/messenger-sandbox.png
Labels: netlify-cms/pending_publish

#401 Update Blog Post “create-custom-ar-filters-with-vonage-video-api-and-deepar”
  content/blog/en/create-custom-ar-filters-with-vonage-video-api-and-deepar.md
  static/content/blog/create-custom-ar-filters-with-vonage-video-api-and-deepar/dog.png
  static/content/blog/create-custom-ar-filters-with-vonage-video-api-and-deepar/header-1.png
  static/content/blog/create-custom-ar-filters-with-vonage-video-api-and-deepar/lion.jpg
  static/content/blog/create-custom-ar-filters-with-vonage-video-api-and-deepar/xcode2.png
Labels: netlify-cms/pending_publish

#410 Create Blog Post “meet-the-first-voyagers-crew-part-4”
  content/blog/en/meet-the-first-voyagers-crew-part-4.md
  static/content/blog/meet-the-first-voyagers-crew-part-4/blog_vonage-voyagers_6_1200x600.png
  static/content/blog/meet-the-first-voyagers-crew-part-4/gabriel.png
  static/content/blog/meet-the-first-voyagers-crew-part-4/matthew-s.png
Labels: netlify-cms/pending_publish

#420 Create Blog Post “migration-from-wordpress-to-jamstack”
  content/blog/en/migration-from-wordpress-to-jamstack.md
  static/content/blog/migration-from-wordpress-to-jamstack/screenshot-2020-11-23-at-13.59.12.png
  static/content/blog/migration-from-wordpress-to-jamstack/screenshot-2020-11-23-at-14.40.57.png
  static/content/blog/migration-from-wordpress-to-jamstack/vonage-learn.png
Labels: netlify-cms/pending_publish

#422 Create Blog Post “how-to-add-two-factor-authentication-with-swift-and-vapor”
  content/blog/en/how-to-add-two-factor-authentication-with-swift-and-vapor.md
  static/content/blog/how-to-add-two-factor-authentication-with-swift-and-vapor/blog_2fa_swift-vapor_1200x600.png
  static/content/blog/how-to-add-two-factor-authentication-with-swift-and-vapor/ngrokterminal.png
  static/content/blog/how-to-add-two-factor-authentication-with-swift-and-vapor/testapp.png
  static/content/blog/how-to-add-two-factor-authentication-with-swift-and-vapor/xcodeterminal.png
Labels: netlify-cms/pending_publish

#436 fix: add authors name to breadcrumb title
  pages/authors/_author.vue
Labels: 🚀  ready-to-go

#437 feat: add vonage.com link in header
  components/Header.vue
Labels: 🚀  ready-to-go

#438 fix: error using object rather than object property for category name
  pages/categories/_category/index.vue
Labels: 🚀  ready-to-go

#439 fix: use flex flex-col space-y-4 to achieve vertical spacing on aside…
  components/RelatedPosts.vue
  components/TableOfContents.vue
  pages/blog/_year/_month/_day/_slug.vue
Labels: 🚀  ready-to-go

#440 fix: tune z-index util classes to layer the overlays, buttons and ima…
  components/BackToTop.vue
  components/Twitch.vue
Labels: 🚀  ready-to-go

#441 feat: add social network sharing buttons to blog aside
  assets/css/main.css
  components/SocialSharing.vue
  nuxt.config.js
  package-lock.json
  package.json
  pages/blog/_year/_month/_day/_slug.vue
  tailwind.config.js
Labels: 🚀  ready-to-go

#442 fix: external links being made relative because they're enclosed in quotes
  content/blog/en/sms-spam-detection-with-machine-learning-in-python.md
Labels: 🚀  ready-to-go

#418 Create Blog Post “text-to-speech-voice-calls-with-go”
  content/blog/en/text-to-speech-voice-calls-with-go.md
  static/content/blog/text-to-speech-voice-calls-with-go/blog_go_text-to-speech_1200x600.png
  static/content/blog/text-to-speech-voice-calls-with-go/voice-feature.png
Labels: netlify-cms/pending_publish

#451 Update Blog Post “text-to-speech-voice-calls-with-go”
  content/blog/en/text-to-speech-voice-calls-with-go.md
Labels: netlify-cms/pending_publish

#461 Update Blog Post “how-to-make-phone-calls-with-swiftui”
  content/blog/en/how-to-make-phone-calls-with-swiftui.md
Labels: netlify-cms/pending_publish

#454 Updates to Author Page & Card
  components/Authors/AuthorCard.vue
  components/Authors/AuthorPage.vue
  pages/authors/_author.vue
  pages/blog/_year/_month/_day/_slug.vue
Labels: 🧙‍♂️  enhancement

#462 Update Authors “lukeoliff”
  content/authors/lukeoliff.json
Labels: netlify-cms/pending_publish

#456 Create Blog Post “server-side-analytics-with-jamstack-sites”
  content/blog/en/server-side-analytics-with-jamstack-sites.md
  static/content/blog/server-side-analytics-with-jamstack-sites/718smiley.svg
  static/content/blog/server-side-analytics-with-jamstack-sites/blog_nuxt_server-side-analytics_1200x600.png
  static/content/blog/server-side-analytics-with-jamstack-sites/screenshot-of-adblock-plus-ignoring-tracker-on-vonage-learn.png
  static/content/blog/server-side-analytics-with-jamstack-sites/screenshot-of-the-smiley-included-in-page.png
Labels: needs-review, netlify-cms/pending_publish

#467 Update Blog Post “server-side-analytics-with-jamstack-sites”
  content/blog/en/server-side-analytics-with-jamstack-sites.md
Labels: netlify-cms/pending_publish

#469 Update Blog Post “server-side-analytics-with-jamstack-sites”
  content/blog/en/server-side-analytics-with-jamstack-sites.md
Labels: netlify-cms/pending_publish
