Repository Nexmo/deved-platform, pull requests merged in 2020-10, with the labels that each got.

#154 Lang Changes
  lang/en-US.js
  lang/it.js
  lang/zh-CN.js
  layouts/default.vue
  nuxt.config.js
Labels: hacktoberfest

#155 nl.js add Dutch translation
  lang/nl.js
Labels: hacktoberfest, hacktoberfest-accepted

#161 Added Norwegian Translations
  lang/nb-NO.js
Labels: hacktoberfest, hacktoberfest-accepted

#167 bug: problem accessing translate function from wrong context
  pages/authors/_author.vue
  pages/authors/index.vue
  pages/blog/_year/_month/_day/_slug.vue
  pages/blog/_year/_month/_day/index.vue
  pages/blog/_year/_month/index.vue
  pages/blog/_year/index.vue
  pages/blog/index.vue
  pages/blog/p/_page.vue
Labels: bug

#185 Update Blog Post “build-an-otp-service-dr”
  content/blog/en/build-an-otp-service-dr.md
  static/content/blog/build-a-one-time-password-otp-service-using-the-dispatch-api/image1.png
  static/content/blog/build-a-one-time-password-otp-service-using-the-dispatch-api/image2.png
  static/content/blog/build-a-one-time-password-otp-service-using-the-dispatch-api/image3.png
  static/content/blog/build-a-one-time-password-otp-service-using-the-dispatch-api/image4.png
Labels: netlify-cms/pending_publish

#183 Update Blog Post “using-jwt-for-authentication-in-a-golang-application-dr”
  content/blog/en/using-jwt-for-authentication-in-a-golang-application-dr.md
  static/content/blog/using-jwt-for-authentication-in-a-golang-application/image1.png
  static/content/blog/using-jwt-for-authentication-in-a-golang-application/image2.png
  static/content/blog/using-jwt-for-authentication-in-a-golang-application/image3.png
  static/content/blog/using-jwt-for-authentication-in-a-golang-application/image4.png
  static/content/blog/using-jwt-for-authentication-in-a-golang-application/image5.png
  static/content/blog/using-jwt-for-authentication-in-a-golang-application/image6.png
  static/content/blog/using-jwt-for-authentication-in-a-golang-application/image7.png
  static/content/blog/using-jwt-for-authentication-in-a-golang-application/image8.png
  static/content/blog/using-jwt-for-authentication-in-a-golang-application/image9.png
Labels: netlify-cms/pending_publish

#191 Update Blog Post “aws-cognito-verify-with-php”
  content/blog/en/aws-cognito-verify-with-php.md
Labels: netlify-cms/pending_publish

#194 Add map to make it possible to consolidate tags
  components/Tag.vue
Labels: enhancement

#193 Update Blog Post “create-websocket-server-java-api-dr”
  content/blog/en/create-websocket-server-java-api-dr.md
  static/content/blog/creating-a-websocket-server-with-the-java-api-for-websockets/2018-10-01-13-38-05.png
  static/content/blog/creating-a-websocket-server-with-the-java-api-for-websockets/2018-10-01-14-23-40.png
Labels: netlify-cms/pending_publish

#196 Update Blog Post “create-websocket-server-spring-boot-dr”
  content/blog/en/create-websocket-server-spring-boot-dr.md
  static/content/blog/creating-a-websocket-server-with-spring-boot/2018-10-01-13-38-05-1-.png
  static/content/blog/creating-a-websocket-server-with-spring-boot/2018-10-01-14-23-40-1-.png
  static/content/blog/creating-a-websocket-server-with-spring-boot/screenshot-2018-10-08-11.14.20.png
Labels: netlify-cms/pending_publish

#197 Update Blog Post “create-websocket-server-java-api-dr”
  content/blog/en/create-websocket-server-java-api-dr.md
Labels: netlify-cms/pending_publish

#198 Update Blog Post “send-sms-messages-asp-net-mvc-framework-dr”
  content/blog/en/send-sms-messages-asp-net-mvc-framework-dr.md
  pages/blog/_slug.vue
  pages/blog/_year/_month/_day/_slug.vue
  static/content/blog/how-to-send-sms-messages-with-asp-net-mvc-framework/installcl.png
  static/content/blog/how-to-send-sms-messages-with-asp-net-mvc-framework/mvc.png
  static/content/blog/how-to-send-sms-messages-with-asp-net-mvc-framework/newproj.png
  static/content/blog/how-to-send-sms-messages-with-asp-net-mvc-framework/sendsms.png
  static/content/blog/how-to-send-sms-messages-with-asp-net-mvc-framework/sms1.jpg
  static/content/blog/how-to-send-sms-messages-with-asp-net-mvc-framework/startbuilding_footer.png
  static/content/blog/how-to-send-sms-messages-with-asp-net-mvc-framework/updatenuget.png
Labels: netlify-cms/pending_publish
