Repository Nexmo/deved-platform, pull requests merged in 2020-09, with the labels that each got.

#117 Update Pages “authors”
  content/authors.json
  static/content/images/dotun.jpeg
Labels: netlify-cms/pending_publish

#118 Create Blog Post “build-a-whatsapp-currency-conversion-bot-with-node-js”
  content/blog/build-a-whatsapp-currency-conversion-bot-with-node-js.md
  static/content/blog/build-a-whatsapp-currency-conversion-bot-with-node-js/blog_node-js_whatsapp_1200x600.png
Labels: netlify-cms/pending_publish

#124 Legacy Content Importer - imports posts from WordPress as stubs to be completed yet
  README.md
  bin/exporter
  content/blog/5-ways-to-build-a-node-js-api.md
  content/blog/7-app-ideas-to-build-at-work-and-7-to-build-at-home-dr.md
  package-lock.json
  package.json
Labels: enhancement

#126 Add redirect frontmatter support
  content/blog/5-ways-to-build-a-node-js-api.md
  content/blog/7-app-ideas-to-build-at-work-and-7-to-build-at-home-dr.md
  pages/blog/_year/_month/_day/_slug.vue
Labels: needs-review
