Repository Nexmo/deved-platform, pull requests merged in 2020-12, with the labels that each got.

#472 Create Authors “sudipto-ghosh”
  content/authors/sudipto-ghosh.json
  static/content/images/sudiptoghosh.jpg
Labels: netlify-cms/pending_publish

#473 Update Blog Post “the-right-way-of-using-gradle-dynamic-dependencies”
  content/blog/en/the-right-way-of-using-gradle-dynamic-dependencies.md
Labels: netlify-cms/pending_publish

#468 Create Blog Post “text-to-speech-let-your-application-speak—now-in-50-languages”
  content/blog/en/text-to-speech-let-your-application-speak—now-in-50-languages.md
  static/content/blog/text-to-speech-let-your-application-speak—now-in-50-languages/text-to-speech1200x600.png
  static/content/blog/text-to-speech-let-your-application-speak—now-in-50-languages/victor1.png
  static/content/blog/text-to-speech-let-your-application-speak—now-in-50-languages/victor2.png
  static/content/blog/text-to-speech-let-your-application-speak—now-in-50-languages/victor3.png
Labels: netlify-cms/pending_publish

#477 Update Blog Post “the-right-way-of-using-gradle-dynamic-dependencies”
  content/blog/en/the-right-way-of-using-gradle-dynamic-dependencies.md
Labels: netlify-cms/pending_publish

#478 Update Blog Post “text-to-speech-let-your-application-speak—now-in-50-languages”
  content/blog/en/text-to-speech-let-your-application-speak—now-in-50-languages.md
Labels: netlify-cms/pending_publish

#485 Update Blog Post “the-right-way-of-using-gradle-dynamic-dependencies”
  content/blog/en/the-right-way-of-using-gradle-dynamic-dependencies.md
Labels: netlify-cms/pending_publish

#486 Update Blog Post “text-to-speech-let-your-application-speak-now-in-50-languages”
  content/blog/en/text-to-speech-let-your-application-speak-now-in-50-languages.md
  static/content/blog/text-to-speech-let-your-application-speak-now-in-50-languages/text-to-speech1200x600.png
Labels: netlify-cms/pending_publish

#471 Create Blog Post “build-an-air-quality-reporting-service-with-messages-api”
  content/blog/en/build-an-air-quality-reporting-service-with-messages-api.md
  static/content/blog/build-an-air-quality-reporting-service-with-messages-api/blog_air-quality-reporting_1200x600.png
  static/content/blog/build-an-air-quality-reporting-service-with-messages-api/ngrok.jpg
  static/content/blog/build-an-air-quality-reporting-service-with-messages-api/receiving.jpg
  static/content/blog/build-an-air-quality-reporting-service-with-messages-api/vonage-aqi-messenger.gif
  static/content/blog/build-an-air-quality-reporting-service-with-messages-api/vonage-aqi-whatsapp.gif
  static/content/blog/build-an-air-quality-reporting-service-with-messages-api/webhook.jpg
Labels: needs-review, netlify-cms/pending_publish

#487 Update Blog Post “text-to-speech-let-your-application-speak-now-in-50-languages”
  content/blog/en/text-to-speech-let-your-application-speak-now-in-50-languages.md
  static/content/blog/text-to-speech-let-your-application-speak-now-in-50-languages/victor1.png
  static/content/blog/text-to-speech-let-your-application-speak-now-in-50-languages/victor2.png
  static/content/blog/text-to-speech-let-your-application-speak-now-in-50-languages/victor3.png
Labels: netlify-cms/pending_publish

#488 Update Authors “sudipto-ghosh”
  content/authors/sudipto-ghosh.json
Labels: netlify-cms/pending_publish

#489 Update Blog Post “text-to-speech-let-your-application-speak-now-in-50-languages”
  content/blog/en/text-to-speech-let-your-application-speak-now-in-50-languages.md
  static/content/blog/text-to-speech-let-your-application-speak-now-in-50-languages/texttospeech-1200x600.png
Labels: netlify-cms/pending_publish

#490 Update Blog Post “text-to-speech-let-your-application-speak-now-in-50-languages”
  content/blog/en/text-to-speech-let-your-application-speak-now-in-50-languages.md
Labels: netlify-cms/pending_publish

#491 Update Blog Post “text-to-speech-let-your-application-speak-now-in-50-languages”
  content/blog/en/text-to-speech-let-your-application-speak-now-in-50-languages.md
Labels: netlify-cms/pending_publish

#492 Update Blog Post “text-to-speech-let-your-application-speak-now-in-50-languages”
  content/blog/en/text-to-speech-let-your-application-speak-now-in-50-languages.md
Labels: netlify-cms/pending_publish

#493 Update Blog Post “text-to-speech-let-your-application-speak-now-in-50-languages”
  content/blog/en/text-to-speech-let-your-application-speak-now-in-50-languages.md
Labels: netlify-cms/pending_publish

#494 Update Blog Post “the-right-way-of-using-gradle-dynamic-dependencies”
  content/blog/en/the-right-way-of-using-gradle-dynamic-dependencies.md
  static/content/blog/the-right-way-of-using-gradle-dynamic-dependencies/avoid-using-plus-character.png
  static/content/blog/the-right-way-of-using-gradle-dynamic-dependencies/change-dependency-version.png
Labels: netlify-cms/pending_publish

#498 Create Blog Post “handle-an-incoming-call-with-go”
  content/blog/en/handle-an-incoming-call-with-go.md
  static/content/blog/handle-an-incoming-call-with-go/blog_go_phone-call_1200x600.png
Labels: netlify-cms/pending_publish

#499 Update Blog Post “go-explore-the-vonage-apis-with-vonage-go-sdk”
  content/blog/en/go-explore-the-vonage-apis-with-vonage-go-sdk.md
Labels: netlify-cms/pending_publish

#500 Update Blog Post “go-explore-the-vonage-apis-with-vonage-go-sdk”
  content/blog/en/go-explore-the-vonage-apis-with-vonage-go-sdk.md
Labels: netlify-cms/pending_publish

#508 Create Authors “solomon-eseme”
  content/authors/solomon-eseme.json
  static/content/images/solomon-eseme.jfif
  static/content/images/solomon-eseme.png
Labels: netlify-cms/pending_publish

#509 Update Blog Post “handle-an-incoming-call-with-go”
  content/blog/en/handle-an-incoming-call-with-go.md
Labels: netlify-cms/pending_publish

#512 Update Blog Post “receiving-an-sms-with-php-dr”
  content/blog/en/receiving-an-sms-with-php-dr.md
Labels: netlify-cms/pending_publish

#425 Create Authors “dennismoyo”
  content/authors/dennismoyo.json
Labels: netlify-cms/pending_publish

#424 Create Blog Post “smart-marketing-with-django-rasa-nlu-and-vonage”
  content/blog/en/smart-marketing-with-django-rasa-nlu-and-vonage.md
  static/content/blog/smart-marketing-with-django-rasa-nlu-and-vonage/blog_automated-marketing_django_1200x600.png
Labels: netlify-cms/pending_publish

#516 Update Blog Post “smart-marketing-with-django-rasa-nlu-and-vonage”
  content/blog/en/smart-marketing-with-django-rasa-nlu-and-vonage.md
Labels: netlify-cms/pending_publish

#517 Update Blog Post “smart-marketing-with-django-rasa-nlu-and-vonage”
  content/blog/en/smart-marketing-with-django-rasa-nlu-and-vonage.md
Labels: netlify-cms/pending_publish

#518 Update Blog Post “smart-marketing-with-django-rasa-nlu-and-vonage”
  content/blog/en/smart-marketing-with-django-rasa-nlu-and-vonage.md
Labels: netlify-cms/pending_publish

#521 Update Authors “dennismoyo”
  content/authors/dennismoyo.json
  static/content/images/img_20201209_113326.jpg
Labels: netlify-cms/pending_publish

#511 Create Blog Post “build-high-availability-voice-api-applications”
  content/blog/en/build-high-availability-voice-api-applications.md
  static/content/blog/build-high-availability-voice-api-applications/blog_high-availability-apps_1200x600.jpg
Labels: netlify-cms/pending_publish

#515 Create Blog Post “using-vonage-apis-with-drupal”
  content/blog/en/using-vonage-apis-with-drupal.md
  static/content/blog/using-vonage-apis-with-drupal/blog_vonageapi_drupal_1200x600.png
  static/content/blog/using-vonage-apis-with-drupal/drupal-install.png
  static/content/blog/using-vonage-apis-with-drupal/first-page.png
  static/content/blog/using-vonage-apis-with-drupal/sms-success.png
Labels: netlify-cms/pending_publish

#524 Update Blog Post “smart-marketing-with-django-rasa-nlu-and-vonage”
  content/blog/en/smart-marketing-with-django-rasa-nlu-and-vonage.md
Labels: netlify-cms/pending_publish

#525 Update Blog Post “smart-marketing-with-django-rasa-nlu-and-vonage”
  content/blog/en/smart-marketing-with-django-rasa-nlu-and-vonage.md
Labels: netlify-cms/pending_publish

#529 Update Authors “solomon-eseme”
  content/authors/solomon-eseme.json
Labels: netlify-cms/pending_publish

#530 Update Authors “victor-steven”
  content/authors/victor-steven.json
  static/content/images/0.png
Labels: netlify-cms/pending_publish

#532 Update Authors “filippos-kyprianou”
  content/authors/filippos-kyprianou.json
Labels: netlify-cms/pending_publish

#533 Update Authors “javier-molina-sanz”
  content/authors/javier-molina-sanz.json
Labels: netlify-cms/pending_publish

#534 Update Authors “hugh-hopkins”
  content/authors/hugh-hopkins.json
Labels: netlify-cms/pending_publish

#535 Update Authors “eric_giannini”
  content/authors/eric_giannini.json
Labels: netlify-cms/pending_publish

#528 Create Blog Post “creating-an-online-classroom-in-laravel-with-vonage-video-api”
  content/blog/en/creating-an-online-classroom-in-laravel-with-vonage-video-api.md
  static/content/blog/creating-an-online-classroom-in-laravel-with-vonage-video-api/blog_online-classroom_laravel_1200x600.png
  static/content/blog/creating-an-online-classroom-in-laravel-with-vonage-video-api/connected-student.png
  static/content/blog/creating-an-online-classroom-in-laravel-with-vonage-video-api/demo-app.jpg
Labels: needs-review, netlify-cms/pending_publish

#541 Update Blog Post “build-an-otp-service-dr”
  content/blog/en/build-an-otp-service-dr.md
Labels: netlify-cms/pending_publish

#542 Create Authors “hector-zelaya”
  content/authors/hector-zelaya.json
  static/content/images/hector.jpg
Labels: netlify-cms/pending_publish

#544 Update Blog Post “receiving-an-sms-with-php-dr”
  content/blog/en/receiving-an-sms-with-php-dr.md
  static/content/blog/receiving-an-sms-with-php/blog_php_sms_1200x600.png
Labels: netlify-cms/pending_publish

#514 Update Blog Post “play-audio-voice-call-php-dr”
  content/blog/en/play-audio-voice-call-php-dr.md
  static/content/blog/play-an-audio-file-into-a-voice-call-with-php/blog_php_audiofile_1200x600.png
Labels: netlify-cms/pending_publish

#538 Create Blog Post “how-to-build-a-learning-platform-using-vonage-javascript-typescript-react-express-and-apollo-graphql”
  content/blog/en/how-to-build-a-learning-platform-using-vonage-javascript-typescript-react-express-and-apollo-graphql.md
  static/content/blog/how-to-build-a-learning-platform-using-vonage-javascript-typescript-react-express-and-apollo-graphql/blog_remote-learning-platform_1200x600.jpg
  static/content/blog/how-to-build-a-learning-platform-using-vonage-javascript-typescript-react-express-and-apollo-graphql/creating_assignment.png
  static/content/blog/how-to-build-a-learning-platform-using-vonage-javascript-typescript-react-express-and-apollo-graphql/passwordless_login.png
  static/content/blog/how-to-build-a-learning-platform-using-vonage-javascript-typescript-react-express-and-apollo-graphql/seeing_assignments.png
  static/content/blog/how-to-build-a-learning-platform-using-vonage-javascript-typescript-react-express-and-apollo-graphql/start_class.png
  static/content/blog/how-to-build-a-learning-platform-using-vonage-javascript-typescript-react-express-and-apollo-graphql/students_page.png
  static/content/blog/how-to-build-a-learning-platform-using-vonage-javascript-typescript-react-express-and-apollo-graphql/uploading_files.png
Labels: needs-review, netlify-cms/pending_publish

#455 Update Authors “julia”
  content/authors/julia.json
  static/content/images/002-putzi-dragon.jpg
Labels: needs-review, netlify-cms/pending_publish

#547 Update Blog Post “how-to-build-a-learning-platform-using-vonage-javascript-typescript-react-express-and-apollo-graphql”
  content/blog/en/how-to-build-a-learning-platform-using-vonage-javascript-typescript-react-express-and-apollo-graphql.md
Labels: netlify-cms/pending_publish

#474 Update Authors “lornajane”
  content/authors/lornajane.json
Labels: needs-review, netlify-cms/draft

#536 Update Authors “glenkunene”
  content/authors/glenkunene.json
Labels: needs-review, netlify-cms/draft

#481 Issues/issue 466/blog page on mobile breadcrumbs author styling tags
  assets/css/main.css
  components/Authors/AuthorCard.vue
  components/Tag.vue
  components/Tags.vue
  pages/blog/_year/_month/_day/_slug.vue
Labels: needs-review, 🐞  bug

#553 Update Authors “dennismoyo”
  content/authors/dennismoyo.json
Labels: netlify-cms/pending_publish

#482 Create Blog Post “create-a-video-help-chat-with-node-js-and-svelte”
  content/blog/en/create-a-video-help-chat-with-node-js-and-svelte.md
  static/content/blog/create-a-video-help-chat-with-node-js-and-svelte/blog_node-js_svelte_video_1200x600.png
Labels: needs-review, netlify-cms/pending_publish

#554 Update Blog Post “create-a-video-help-chat-with-node-js-and-svelte”
  content/blog/en/create-a-video-help-chat-with-node-js-and-svelte.md
Labels: netlify-cms/pending_publish

#566 Create Blog Post “all-i-want-for-christmas-is-ruby-3”
  content/blog/en/all-i-want-for-christmas-is-ruby-3.md
  static/content/blog/all-i-want-for-christmas-is-ruby-3/blog_ruby-christmas_1200x600.jpg
Labels: netlify-cms/pending_publish

#548 Update Blog Post “how-to-build-a-learning-platform-using-vonage-javascript-typescript-react-express-and-apollo-graphql”
  content/blog/en/how-to-build-a-learning-platform-using-vonage-javascript-typescript-react-express-and-apollo-graphql.md
  static/content/blog/how-to-build-a-learning-platform-with-react-express-and-apollo-graphql/creating_assignment.png
  static/content/blog/how-to-build-a-learning-platform-with-react-express-and-apollo-graphql/passwordless_login.png
  static/content/blog/how-to-build-a-learning-platform-with-react-express-and-apollo-graphql/seeing_assignments.png
  static/content/blog/how-to-build-a-learning-platform-with-react-express-and-apollo-graphql/uploading_files.png
Labels: needs-review, netlify-cms/pending_publish

#567 Update Blog Post “all-i-want-for-christmas-is-ruby-3”
  content/blog/en/all-i-want-for-christmas-is-ruby-3.md
Labels: netlify-cms/pending_publish

#568 Update Blog Post “all-i-want-for-christmas-is-ruby-3”
  content/blog/en/all-i-want-for-christmas-is-ruby-3.md
Labels: netlify-cms/pending_publish

#570 Create Blog Post “build-a-secret-santa-app-with-blazor”
  content/blog/en/build-a-secret-santa-app-with-blazor.md
  static/content/blog/build-a-secret-santa-app-with-blazor/blog_secret-santa_blazor_1200x600.jpg
Labels: netlify-cms/pending_publish

#546 Create Blog Post “roadmap-to-2021-making-things-happen-1”
  content/blog/en/roadmap-to-2021-making-things-happen-1.md
  static/content/blog/roadmap-to-2021-making-things-happen/roadmap-2021.png
Labels: needs-review, netlify-cms/pending_publish

#565 Update Blog Post “using-vonage-apis-with-drupal”
  content/blog/en/using-vonage-apis-with-drupal.md
Labels: needs-review, netlify-cms/pending_publish

#575 Update Blog Post “roadmap-to-2021-making-things-happen-1”
  content/blog/en/roadmap-to-2021-making-things-happen-1.md
Labels: netlify-cms/pending_publish

#444 Update Blog Post “12-bots-to-better-your-open-source-project”
  content/blog/en/12-bots-to-better-your-open-source-project.md
Labels: needs-review, netlify-cms/draft
