Repository Nexmo/deved-platform, pull requests merged in 2021-01, with the labels that each got.

#597 Create Blog Post “visual-studio-code-extensions-to-enhance-productivity-in-2021”
  content/blog/en/visual-studio-code-extensions-to-enhance-productivity-in-2021.md
  static/content/blog/visual-studio-code-extensions-to-enhance-productivity-in-2021/better-comments.png
  static/content/blog/visual-studio-code-extensions-to-enhance-productivity-in-2021/blog_visualstudioextensions.png
  static/content/blog/visual-studio-code-extensions-to-enhance-productivity-in-2021/bracket-pair.png
  static/content/blog/visual-studio-code-extensions-to-enhance-productivity-in-2021/intellisense.gif
  static/content/blog/visual-studio-code-extensions-to-enhance-productivity-in-2021/peacock.jpg
  static/content/blog/visual-studio-code-extensions-to-enhance-productivity-in-2021/quokka.gif
Labels: netlify-cms/pending_publish

#598 Create Blog Post “introducing-the-ios-push-certificate-uploader”
  content/blog/en/introducing-the-ios-push-certificate-uploader.md
  static/content/blog/introducing-the-ios-push-certificate-uploader/app.png
  static/content/blog/introducing-the-ios-push-certificate-uploader/blog_ios_push_certificate.png
  static/content/blog/introducing-the-ios-push-certificate-uploader/successfulapp.png
Labels: netlify-cms/pending_publish

#586 fix: nuxt trailing slashes enabled
  components/Breadcrumbs.vue
  components/Footer.vue
  nuxt.config.js
Labels: needs-review

#587 fix: clear algolia index before adding records to it
  netlify-plugins/algolia-export/index.js
Labels: needs-review

#588 fix: opensearch url still wrong
  static/search.xml
Labels: needs-review

#604 Create Blog Post “how-to-send-sms-messages-with-swift-vapor-and-vonage”
  content/blog/en/how-to-send-sms-messages-with-swift-vapor-and-vonage.md
  static/content/blog/how-to-send-sms-messages-with-swift-vapor-and-vonage/blog_sms_swift-vapor_1200x600.png
  static/content/blog/how-to-send-sms-messages-with-swift-vapor-and-vonage/input.png
  static/content/blog/how-to-send-sms-messages-with-swift-vapor-and-vonage/response.png
  static/content/blog/how-to-send-sms-messages-with-swift-vapor-and-vonage/workingdir.png
Labels: netlify-cms/pending_publish

#610 Create Blog Post “telephone-number-insights-from-vonage-with-go”
  content/blog/en/telephone-number-insights-from-vonage-with-go.md
  static/content/blog/telephone-number-insights-from-vonage-with-go/go_numberinsight_1200x600.png
Labels: netlify-cms/pending_publish

#608 Create Blog Post “play-an-audio-file-into-a-voice-call-with-go”
  content/blog/en/play-an-audio-file-into-a-voice-call-with-go.md
  static/content/blog/play-an-audio-file-into-a-voice-call-with-go/go_audioincall1200x600.png
Labels: needs-review, netlify-cms/pending_publish

#627 Create Blog Post “introducing-the-vonage-voice-api-on-zapier”
  content/blog/en/introducing-the-vonage-voice-api-on-zapier.md
  static/content/blog/introducing-the-vonage-voice-api-on-zapier/kotlin_ktor_2fa_1200x600_white.png
  static/content/blog/introducing-the-vonage-voice-api-on-zapier/vonage-voice-actions-zapier.png
  static/content/blog/introducing-the-vonage-voice-api-on-zapier/vonage-voice-triggers-zapier.png
Labels: netlify-cms/pending_publish

#612 Create Blog Post “build-a-2fa-server-with-kotlin-and-ktor”
  content/blog/en/build-a-2fa-server-with-kotlin-and-ktor.md
  static/content/blog/build-a-2fa-server-with-kotlin-and-ktor/app-is-working.png
  static/content/blog/build-a-2fa-server-with-kotlin-and-ktor/kotlin_ktor_2fa_1200x600_white.png
  static/content/blog/build-a-2fa-server-with-kotlin-and-ktor/run-app.png
Labels: needs-review, netlify-cms/pending_publish

#628 Update Blog Post “introducing-the-vonage-voice-api-on-zapier”
  content/blog/en/introducing-the-vonage-voice-api-on-zapier.md
  static/content/blog/introducing-the-vonage-voice-api-on-zapier/zapiervoice1200x600.png
Labels: netlify-cms/pending_publish

#639 Create Blog Post “vonage-attends-hack-the-north-2020”
  content/blog/en/vonage-attends-hack-the-north-2020.md
  static/content/blog/vonage-attends-hack-the-north-2020/hackthenorth1200x600.png
Labels: netlify-cms/pending_publish

#640 Update Blog Post “vonage-attends-hack-the-north-2020”
  content/blog/en/vonage-attends-hack-the-north-2020.md
Labels: netlify-cms/pending_publish

#641 Update Blog Post “smart-marketing-with-django-rasa-nlu-and-vonage”
  content/blog/en/smart-marketing-with-django-rasa-nlu-and-vonage.md
Labels: netlify-cms/pending_publish

#643 Create Blog Post “handling-voip-push-notifications-with-callkit”
  content/blog/en/handling-voip-push-notifications-with-callkit.md
  static/content/blog/handling-voip-push-notifications-with-callkit/activecall.png
  static/content/blog/handling-voip-push-notifications-with-callkit/add-capability.png
  static/content/blog/handling-voip-push-notifications-with-callkit/add-certificate.png
  static/content/blog/handling-voip-push-notifications-with-callkit/background-modes.png
  static/content/blog/handling-voip-push-notifications-with-callkit/callkit-push-notifications1200x600.png
  static/content/blog/handling-voip-push-notifications-with-callkit/callkitframework.png
  static/content/blog/handling-voip-push-notifications-with-callkit/gist.png
  static/content/blog/handling-voip-push-notifications-with-callkit/keychain-export.png
  static/content/blog/handling-voip-push-notifications-with-callkit/lockedcall.png
  static/content/blog/handling-voip-push-notifications-with-callkit/pushupload.png
  static/content/blog/handling-voip-push-notifications-with-callkit/signing.png
Labels: netlify-cms/pending_publish

#646 Update Blog Post “daniela-joins-the-nexmo-developer-relations-team-dr”
  content/blog/en/daniela-joins-the-nexmo-developer-relations-team-dr.md
Labels: netlify-cms/pending_publish
