Repository Nexmo/deved-platform, pull requests merged in 2021-04, with the labels that each got.

#838 Update Blog Post “make-app-to-phone-call-using-ios-and-flutter”
  content/blog/en/make-app-to-phone-call-using-ios-and-flutter.md
  static/content/blog/make-app-to-phone-call-using-ios-and-flutter/loggedout.png
  static/content/blog/make-app-to-phone-call-using-ios-and-flutter/makeaphonecall.png
  static/content/blog/make-app-to-phone-call-using-ios-and-flutter/oncall.png
  static/content/blog/make-app-to-phone-call-using-ios-and-flutter/ui-states.png
Labels: needs-review, netlify-cms/pending_publish

#904 Update Blog Post “make-app-to-phone-call-using-ios-and-flutter”
  content/blog/en/make-app-to-phone-call-using-ios-and-flutter.md
  static/content/blog/make-app-to-phone-call-using-ios-and-flutter/flutter_inapp-call-2_1200x600.png
Labels: netlify-cms/pending_publish

#889 Updating author profile for MJ
  content/authors/michaeljolley.json
Labels: needs-review

#916 Create Authors “caroline-kerns”
  content/authors/caroline-kerns.json
  static/content/images/carokerns.png
Labels: netlify-cms/pending_publish

#918 Create Blog Post “caroline-kerns-joins-the-vonage-developer-relations-team”
  content/blog/en/caroline-kerns-joins-the-vonage-developer-relations-team.md
  static/content/blog/caroline-kerns-joins-the-vonage-developer-relations-team/caroline-kerns.png
Labels: netlify-cms/pending_publish

#929 Update Blog Post “make-app-to-phone-call-using-android-and-flutter”
  content/blog/en/make-app-to-phone-call-using-android-and-flutter.md
Labels: netlify-cms/pending_publish

#917 Create Blog Post “random-fact-voice-call-with-php-uselessfacts-and-aws-lambda”
  content/blog/en/random-fact-voice-call-with-php-uselessfacts-and-aws-lambda.md
  static/content/blog/random-fact-voice-call-with-php-uselessfacts-and-aws-lambda/serverless-deployment-success.png
  static/content/blog/random-facts-voice-call-with-php-uselessfacts-and-aws-lambda/useless-facts_php_1200x600.png
Labels: needs-review, netlify-cms/pending_publish

#930 Update Blog Post “handling-voip-push-notifications-with-callkit”
  content/blog/en/handling-voip-push-notifications-with-callkit.md
  static/content/blog/handling-voip-push-notifications-with-callkit/activecallsm.png
  static/content/blog/handling-voip-push-notifications-with-callkit/loackedcallsm.png
Labels: netlify-cms/pending_publish

#931 Update Blog Post “how-to-add-two-factor-authentication-with-swift-and-vapor”
  content/blog/en/how-to-add-two-factor-authentication-with-swift-and-vapor.md
  static/content/blog/how-to-add-two-factor-authentication-with-swift-and-vapor/testappnew.png
Labels: netlify-cms/pending_publish

#927 Create Blog Post “startup-spotlight-series-billseye”
  content/blog/en/startup-spotlight-series-billseye.md
  static/content/blog/startup-spotlight-lets-meet-billseye/startups_billseye_1200x600.png
Labels: needs-review, netlify-cms/pending_publish

#937 Update Blog Post “startup-spotlight-series-billseye”
  content/blog/en/startup-spotlight-series-billseye.md
Labels: netlify-cms/pending_publish

#938 Update Blog Post “startup-spotlight-series-billseye”
  content/blog/en/startup-spotlight-series-billseye.md
Labels: netlify-cms/pending_publish

#969 Create Authors “jo-frank”
  content/authors/jo-frank.json
  static/content/images/eg4ciosh_400x400.jpg
Labels: netlify-cms/pending_publish

#919 Create Blog Post “how-to-make-phone-calls-using-ios-and-react-native”
  content/blog/en/how-to-make-phone-calls-using-ios-and-react-native.md
  static/content/blog/how-to-make-phone-calls-using-ios-and-react-native/arch.png
  static/content/blog/how-to-make-phone-calls-using-ios-and-react-native/gist.png
  static/content/blog/how-to-make-phone-calls-using-ios-and-react-native/login.png
  static/content/blog/how-to-make-phone-calls-using-ios-and-react-native/react_inapp-call_ios_1200x600.png
  static/content/blog/how-to-make-phone-calls-using-ios-and-react-native/ui.png
Labels: needs-review, netlify-cms/pending_publish

#949 Create Blog Post “startup-community-partner-dms-accelerator”
  content/blog/en/startup-community-partner-dms-accelerator.md
  static/content/blog/startup-community-partner-dms-accelerator/startups_dms_1200x600.png
Labels: needs-review, netlify-cms/pending_publish

#972 Update Blog Post “startup-community-partner-dms-accelerator”
  content/blog/en/startup-community-partner-dms-accelerator.md
Labels: netlify-cms/pending_publish

#959 Update Blog Post “add-2fa-to-nuxt-with-nexmo-verify-dr”
  content/blog/en/add-2fa-to-nuxt-with-nexmo-verify-dr.md
  static/content/blog/add-2fa-to-your-nuxt-application-with-nexmo-verify/login-page.png
  static/content/blog/add-2fa-to-your-nuxt-application-with-nexmo-verify/pin-entry.png
Labels: needs-review, netlify-cms/pending_publish

#954 Update Blog Post “speech-to-text-with-nexmo-and-azure-speech-dr”
  content/blog/en/speech-to-text-with-nexmo-and-azure-speech-dr.md
  static/content/blog/speech-to-text-with-nexmo-and-microsoft-azure/ms-speect-to-text-2.png
Labels: needs-review, netlify-cms/pending_publish

#950 Update Blog Post “introducing-the-vonage-reports-api”
  content/blog/en/introducing-the-vonage-reports-api.md
Labels: needs-review, netlify-cms/pending_publish

#956 Update Blog Post “real-time-number-insight-dashboard-dr”
  content/blog/en/real-time-number-insight-dashboard-dr.md
Labels: needs-review, netlify-cms/pending_publish

#948 Update Blog Post “greg-holmes-joins-the-vonage-developer-education-team”
  content/blog/en/greg-holmes-joins-the-vonage-developer-education-team.md
Labels: needs-review, netlify-cms/pending_publish

#942 Update Blog Post “how-to-create-a-pull-request-with-github-desktop”
  content/blog/en/how-to-create-a-pull-request-with-github-desktop.md
  static/content/blog/how-to-create-a-pull-request-with-github-desktop/check-any-build-tests-pass.png
  static/content/blog/how-to-create-a-pull-request-with-github-desktop/compare-changes-in-github-desktop.png
  static/content/blog/how-to-create-a-pull-request-with-github-desktop/create-pull-request.png
  static/content/blog/how-to-create-a-pull-request-with-github-desktop/push-changes.png
  static/content/blog/how-to-create-a-pull-request-with-github-desktop/review-pull-request-before-submitting.png
  static/content/blog/how-to-create-a-pull-request-with-github-desktop/review-submitted-pull-request.png
  static/content/blog/how-to-create-a-pull-request-with-github-desktop/write-commit-message-and-description.png
Labels: needs-review, netlify-cms/pending_publish

#965 Update Blog Post “comparing-cli-building-libraries”
  content/blog/en/comparing-cli-building-libraries.md
Labels: needs-review, netlify-cms/pending_publish

#962 Update Blog Post “variables-and-chaining-requests-in-postman”
  content/blog/en/variables-and-chaining-requests-in-postman.md
  static/content/blog/using-variables-and-chaining-requests-in-postman/get-account-balance.png
  static/content/blog/using-variables-and-chaining-requests-in-postman/set-as-new-variable-dupl.png
  static/content/blog/using-variables-and-chaining-requests-in-postman/vonage-collection-postman.png
  static/content/blog/using-variables-and-chaining-requests-in-postman/vonage-environment-in-postman.png
Labels: needs-review, netlify-cms/pending_publish

#960 Update Blog Post “record-a-phone-message-with-php-dr”
  content/blog/en/record-a-phone-message-with-php-dr.md
Labels: needs-review, netlify-cms/pending_publish

#945 Update Blog Post “home-surveillance-system-with-node-and-a-raspberry-pi”
  content/blog/en/home-surveillance-system-with-node-and-a-raspberry-pi.md
Labels: needs-review, netlify-cms/pending_publish

#961 Update Blog Post “handle-user-input-with-php-dr”
  content/blog/en/handle-user-input-with-php-dr.md
Labels: needs-review, netlify-cms/pending_publish

#935 Create Blog Post “server-side-analytics-with-jamstack-sites-1”
  content/blog/en/server-side-analytics-with-jamstack-sites-1.md
Labels: needs-review, netlify-cms/pending_publish

#952 Update Blog Post “how-to-send-sms-with-go-dr”
  content/blog/en/how-to-send-sms-with-go-dr.md
Labels: needs-review, netlify-cms/pending_publish

#943 Update Blog Post “an-introduction-to-git-dr”
  content/blog/en/an-introduction-to-git-dr.md
  static/content/blog/an-introduction-to-git/create-github-repo.png
  static/content/blog/an-introduction-to-git/git-status.png
  static/content/blog/an-introduction-to-git/git-version.png
  static/content/blog/an-introduction-to-git/github-repo-created.png
Labels: needs-review, netlify-cms/pending_publish

#944 Update Blog Post “send-raspberry-pi-ip-address-on-boot-in-node-with-messages”
  content/blog/en/send-raspberry-pi-ip-address-on-boot-in-node-with-messages.md
Labels: needs-review, netlify-cms/pending_publish

#946 Update Blog Post “befriending-service-with-symfony-and-vonage”
  content/blog/en/befriending-service-with-symfony-and-vonage.md
  static/content/blog/befriending-service-with-symfony-and-vonage/docker-up.png
  static/content/blog/befriending-service-with-symfony-and-vonage/fresh-symfony-structure.png
  static/content/blog/befriending-service-with-symfony-and-vonage/ngrok-status-page-1.png
  static/content/blog/befriending-service-with-symfony-and-vonage/register-view.png
  static/content/blog/befriending-service-with-symfony-and-vonage/registration-page.png
  static/content/blog/befriending-service-with-symfony-and-vonage/verify-form-creation.png
Labels: needs-review, netlify-cms/pending_publish

#973 Update Blog Post “startup-community-partner-dms-accelerator”
  content/blog/en/startup-community-partner-dms-accelerator.md
Labels: netlify-cms/pending_publish

#974 Update Blog Post “startup-spotlight-series-billseye”
  content/blog/en/startup-spotlight-series-billseye.md
Labels: netlify-cms/pending_publish

#947 Update Blog Post “verify-user-registrations-with-symfony-dr”
  content/blog/en/verify-user-registrations-with-symfony-dr.md
  static/content/blog/verify-user-registrations-with-symfony/docker-up.png
  static/content/blog/verify-user-registrations-with-symfony/initial-register.png
  static/content/blog/verify-user-registrations-with-symfony/register-form.png
  static/content/blog/verify-user-registrations-with-symfony/verify-form.png
  static/content/blog/verify-user-registrations-with-symfony/verify-subscriber.png
Labels: needs-review, netlify-cms/pending_publish

#958 Update Blog Post “nexmo-messages-dispatch-apis-dr”
  content/blog/en/nexmo-messages-dispatch-apis-dr.md
  static/content/blog/first-look-at-the-nexmo-messages-and-dispatch-apis/messages-dispatch-overview-1.png
Labels: needs-review, netlify-cms/pending_publish

#967 Update Blog Post “add-overlay-to-video-with-the-vonage-video-api”
  content/blog/en/add-overlay-to-video-with-the-vonage-video-api.md
  static/content/blog/add-overlay-to-video-with-the-vonage-video-api/text-overlay.png
  static/content/blog/add-overlay-to-video-with-the-vonage-video-api/three-canvases.png
Labels: needs-review, netlify-cms/pending_publish

#976 Update Blog Post “whatsapp-analytics-spatial-mapping-of-users-of-whatsapp-groups”
  content/blog/en/whatsapp-analytics-spatial-mapping-of-users-of-whatsapp-groups.md
Labels: netlify-cms/pending_publish

#920 Create Blog Post “how-to-make-phone-calls-using-android-and-react-native”
  content/blog/en/how-to-make-phone-calls-using-android-and-react-native.md
  static/content/blog/how-to-make-phone-calls-using-android-and-react-native/arch.png
  static/content/blog/how-to-make-phone-calls-using-android-and-react-native/avd.png
  static/content/blog/how-to-make-phone-calls-using-android-and-react-native/emulator.png
  static/content/blog/how-to-make-phone-calls-using-android-and-react-native/gist.png
  static/content/blog/how-to-make-phone-calls-using-android-and-react-native/gist1.png
  static/content/blog/how-to-make-phone-calls-using-android-and-react-native/login.png
  static/content/blog/how-to-make-phone-calls-using-android-and-react-native/react_inapp-call_android_1200x600.png
  static/content/blog/how-to-make-phone-calls-using-android-and-react-native/ui.png
Labels: needs-review, netlify-cms/pending_publish

#977 Update Authors “jo-frank”
  content/authors/jo-frank.json
  static/content/images/img_20180208_084301_mr1518105078861.jpg
Labels: netlify-cms/pending_publish

#953 Update Blog Post “how-to-send-mms-with-node-js-dr”
  content/blog/en/how-to-send-mms-with-node-js-dr.md
Labels: needs-review, netlify-cms/pending_publish

#963 Create Blog Post “show-sms-notifications-in-the-browser-with-next-js-ably-and-vercel”
  content/blog/en/show-sms-notifications-in-the-browser-with-next-js-ably-and-vercel.md
Labels: needs-review, netlify-cms/pending_publish

#964 Update Blog Post “basic-video-chat”
  content/blog/en/basic-video-chat.md
Labels: needs-review, netlify-cms/pending_publish

#951 Update Blog Post “introducing-the-messages-api-sandbox”
  content/blog/en/introducing-the-messages-api-sandbox.md
  static/content/blog/introducing-the-messages-api-sandbox/code-block.png
  static/content/blog/introducing-the-messages-api-sandbox/external-accounts.png
  static/content/blog/introducing-the-messages-api-sandbox/received-message.jpeg
  static/content/blog/introducing-the-messages-api-sandbox/webhooks.png
  static/content/blog/introducing-the-messages-api-sandbox/whitelist-options-small.png
Labels: needs-review, netlify-cms/pending_publish

#939 Create Blog Post “introducing-the-client-sdk-ui-web-components”
  content/blog/en/introducing-the-client-sdk-ui-web-components.md
  static/content/blog/introducing-the-client-sdk-ui-web-components/app-to-phone-with-keypad.jpg
  static/content/blog/introducing-the-client-sdk-ui-web-components/client-sdk-ui-web-components_1200x627.png
  static/content/blog/introducing-the-client-sdk-ui-web-components/wc-chat-layout-highlight.jpg
Labels: needs-review, netlify-cms/pending_publish

#980 Update Blog Post “make-outbound-text-speech-phone-call-node-js-dr”
  content/blog/en/make-outbound-text-speech-phone-call-node-js-dr.md
Labels: netlify-cms/pending_publish

#981 Update Authors “michaeljolley”
  content/authors/michaeljolley.json
  static/content/images/michael_jolley.jfif
Labels: netlify-cms/pending_publish

#984 Update Blog Post “introducing-the-client-sdk-ui-web-components”
  content/blog/en/introducing-the-client-sdk-ui-web-components.md
Labels: netlify-cms/pending_publish

#985 Update Blog Post “how-to-send-a-facebook-messenger-message-with-node-js”
  content/blog/en/how-to-send-a-facebook-messenger-message-with-node-js.md
Labels: netlify-cms/pending_publish

#983 Update Blog Post “how-to-make-phone-calls-using-android-and-react-native”
  content/blog/en/how-to-make-phone-calls-using-android-and-react-native.md
Labels: netlify-cms/pending_publish

#989 Update Blog Post “how-to-make-phone-calls-using-android-and-react-native”
  content/blog/en/how-to-make-phone-calls-using-android-and-react-native.md
Labels: netlify-cms/pending_publish

#999 Update Blog Post “build-a-video-conversation-platform-for-online-gatherings-with-nuxt-js-dr”
  content/blog/en/build-a-video-conversation-platform-for-online-gatherings-with-nuxt-js-dr.md
  static/content/blog/build-a-video-conversation-platform-for-online-gatherings-with-nuxt-js/embed-id.png
  static/content/blog/build-a-video-conversation-platform-for-online-gatherings-with-nuxt-js/event-lobby.png
  static/content/blog/build-a-video-conversation-platform-for-online-gatherings-with-nuxt-js/video-call-extra-info.png
  static/content/blog/build-a-video-conversation-platform-for-online-gatherings-with-nuxt-js/video-call.png
Labels: netlify-cms/pending_publish

#926 Update Blog Post “how-to-build-an-on-call-application-with-react-native-and-symfony”
  content/blog/en/how-to-build-an-on-call-application-with-react-native-and-symfony.md
Labels: needs-review, netlify-cms/pending_publish

#941 Update Blog Post “introducing-google-verified-sms-with-vonage”
  content/blog/en/introducing-google-verified-sms-with-vonage.md
Labels: needs-review, netlify-cms/pending_publish

#996 Update Blog Post “validate-telephone-number-python-dr”
  content/blog/en/validate-telephone-number-python-dr.md
Labels: netlify-cms/pending_publish

#1001 Update Blog Post “text-when-you-get-home-safely-with-zapier-dr”
  content/blog/en/text-when-you-get-home-safely-with-zapier-dr.md
  static/content/blog/text-when-you-get-home-safely-with-zapier/flic-button.jpeg
  static/content/blog/text-when-you-get-home-safely-with-zapier/flic-config3.png
  static/content/blog/text-when-you-get-home-safely-with-zapier/home-page.png
  static/content/blog/text-when-you-get-home-safely-with-zapier/sms-settings.png
  static/content/blog/text-when-you-get-home-safely-with-zapier/then-sms-zap.png
  static/content/blog/text-when-you-get-home-safely-with-zapier/zap-is-on.png
Labels: netlify-cms/pending_publish

#968 Update Blog Post “ngrok-in-node-red-dr”
  content/blog/en/ngrok-in-node-red-dr.md
  static/content/blog/getting-started-with-ngrok-in-node-red/ngrok-authtoken.png
  static/content/blog/getting-started-with-ngrok-in-node-red/ngrok-dashoard.png
  static/content/blog/getting-started-with-ngrok-in-node-red/ngrok-manage-palette.png
  static/content/blog/getting-started-with-ngrok-in-node-red/ngrok-node-properties.png
  static/content/blog/getting-started-with-ngrok-in-node-red/ngrok-nodered.png
  static/content/blog/getting-started-with-ngrok-in-node-red/ngrok-terminal.png
  static/content/blog/getting-started-with-ngrok-in-node-red/replay-ngrok.png
Labels: needs-review, netlify-cms/pending_publish

#957 Update Blog Post “build-a-facebook-messenger-bot-with-messages-api-and-dialogflow-dr”
  content/blog/en/build-a-facebook-messenger-bot-with-messages-api-and-dialogflow-dr.md
Labels: needs-review, netlify-cms/pending_publish

#966 Update Blog Post “build-chat-app-angular-material-stitch-javascript-dr”
  content/blog/en/build-chat-app-angular-material-stitch-javascript-dr.md
Labels: needs-review, netlify-cms/pending_publish

#1000 Update Blog Post “build-a-secure-video-appointments-application-using-vonage-api-dr”
  content/blog/en/build-a-secure-video-appointments-application-using-vonage-api-dr.md
  static/content/blog/build-a-secure-video-appointments-application-using-vonage-api/healthcare-video-appointment.png
Labels: netlify-cms/pending_publish

#955 Update Blog Post “break-awkward-silences-with-terrible-festive-jokes-via-sms-dr”
  content/blog/en/break-awkward-silences-with-terrible-festive-jokes-via-sms-dr.md
Labels: needs-review, netlify-cms/pending_publish

#997 Update Blog Post “supporting-communities-to-go-online”
  content/blog/en/supporting-communities-to-go-online.md
  static/content/blog/supporting-communities-to-go-online/remo.png
  static/content/blog/supporting-communities-to-go-online/social-cafe-.png
Labels: netlify-cms/pending_publish

#1002 Update Blog Post “building-a-check-in-app-with-nexmos-verify-api-dr”
  content/blog/en/building-a-check-in-app-with-nexmos-verify-api-dr.md
Labels: netlify-cms/pending_publish

#995 Update Blog Post “getting-started-with-advanced-insights”
  content/blog/en/getting-started-with-advanced-insights.md
  static/content/blog/getting-started-with-advanced-insights/graphql_object_def.png
  static/content/blog/getting-started-with-advanced-insights/graphql_query_flow.png
  static/content/blog/getting-started-with-advanced-insights/insights_dashboard.png
  static/content/blog/getting-started-with-advanced-insights/inspector_qual_metric-1.png
  static/content/blog/getting-started-with-advanced-insights/inspector_qual_metric.png
  static/content/blog/getting-started-with-advanced-insights/sample_pub_chart-1.png
  static/content/blog/getting-started-with-advanced-insights/sample_pub_chart.png
  static/content/blog/getting-started-with-advanced-insights/sessiondata_schema.png
  static/content/blog/getting-started-with-advanced-insights/sessionsummaries_schema.png
Labels: netlify-cms/pending_publish

#982 Update Blog Post “how-to-make-phone-calls-using-ios-and-react-native”
  content/blog/en/how-to-make-phone-calls-using-ios-and-react-native.md
Labels: needs-review, netlify-cms/pending_publish

#1005 Create Authors “daniela-facchinetti”
  content/authors/daniela-facchinetti.json
  static/content/images/230962_10151269310519515_797260551_n.jpg
Labels: netlify-cms/pending_publish

#1003 Update Blog Post “shipping-notifications-on-wordpress-woocommerce-with-nexmo-sms-dr”
  content/blog/en/shipping-notifications-on-wordpress-woocommerce-with-nexmo-sms-dr.md
  static/content/blog/shipping-notifications-on-wordpress-woocommerce-powered-by-nexmo-sms/wordpress1.png
  static/content/blog/shipping-notifications-on-wordpress-woocommerce-powered-by-nexmo-sms/wordpress3.png
  static/content/blog/shipping-notifications-on-wordpress-woocommerce-powered-by-nexmo-sms/worpress2.png
  static/content/blog/shipping-notifications-on-wordpress-woocommerce-powered-by-nexmo-sms/worpress4.png
Labels: netlify-cms/pending_publish

#1004 Update Blog Post “sentiment-analysis-using-ibm-watson-tone-analyzer-in-php-dr”
  content/blog/en/sentiment-analysis-using-ibm-watson-tone-analyzer-in-php-dr.md
  static/content/blog/sentiment-analysis-using-ibm-watson-tone-analyzer-in-php/watson-create_resource.png
  static/content/blog/sentiment-analysis-using-ibm-watson-tone-analyzer-in-php/watson-nexmo_dashboard.png
  static/content/blog/sentiment-analysis-using-ibm-watson-tone-analyzer-in-php/watson-nexmo_hooks.png
  static/content/blog/sentiment-analysis-using-ibm-watson-tone-analyzer-in-php/watson-tone_analyzer_service.png
Labels: netlify-cms/pending_publish

#1006 Update Blog Post “using-message-signatures-to-ensure-secure-incoming-webhooks-dr”
  content/blog/en/using-message-signatures-to-ensure-secure-incoming-webhooks-dr.md
Labels: netlify-cms/pending_publish

#1007 Update Blog Post “discover-your-twitters-positivity-score-with-react-dr”
  content/blog/en/discover-your-twitters-positivity-score-with-react-dr.md
  static/content/blog/discover-your-twitter’s-positivity-score-with-react/architecture.png
Labels: netlify-cms/pending_publish

#1008 Update Blog Post “ivr-java-spark-framework-dr”
  content/blog/en/ivr-java-spark-framework-dr.md
Labels: netlify-cms/pending_publish

#1011 Update Authors “jo-frank”
  content/authors/jo-frank.json
Labels: netlify-cms/pending_publish

#1009 Update Blog Post “sms-language-understanding-with-luis-and-net-dr”
  content/blog/en/sms-language-understanding-with-luis-and-net-dr.md
  static/content/blog/sms-language-understanding-with-luis-and-net/aftertraining.png
  static/content/blog/sms-language-understanding-with-luis-and-net/build.png
  static/content/blog/sms-language-understanding-with-luis-and-net/create_app.png
  static/content/blog/sms-language-understanding-with-luis-and-net/createaddresstype.gif
  static/content/blog/sms-language-understanding-with-luis-and-net/createmethodentity.gif
  static/content/blog/sms-language-understanding-with-luis-and-net/entitieshighlighted.png
  static/content/blog/sms-language-understanding-with-luis-and-net/ezgif.com-optimize-1.gif
  static/content/blog/sms-language-understanding-with-luis-and-net/ezgif.com-optimize-6.gif
  static/content/blog/sms-language-understanding-with-luis-and-net/ngrok.png
Labels: netlify-cms/pending_publish

#1014 Update Blog Post “random-fact-voice-call-with-php-uselessfacts-and-aws-lambda”
  content/blog/en/random-fact-voice-call-with-php-uselessfacts-and-aws-lambda.md
Labels: netlify-cms/pending_publish

#1015 Update Blog Post “discover-your-twitters-positivity-score-with-react-dr”
  content/blog/en/discover-your-twitters-positivity-score-with-react-dr.md
Labels: netlify-cms/pending_publish

#979 Update Blog Post “show-sms-notifications-in-the-browser-with-next-js-ably-and-vercel”
  content/blog/en/show-sms-notifications-in-the-browser-with-next-js-ably-and-vercel.md
  static/content/blog/show-sms-notifications-in-the-browser-with-next-js-ably-and-vercel/ably_vonage_1200x600.png
Labels: needs-review, netlify-cms/pending_publish

#1017 Update Blog Post “opentok-v2-16-new-release”
  content/blog/en/opentok-v2-16-new-release.md
Labels: netlify-cms/pending_publish

#1018 Update Blog Post “build-an-ivr-with-ruby-on-rails-dr”
  content/blog/en/build-an-ivr-with-ruby-on-rails-dr.md
  static/content/blog/how-to-build-a-simple-ivr-with-ruby-on-rails/buy-numbers-menu.png
  static/content/blog/how-to-build-a-simple-ivr-with-ruby-on-rails/edit-number-menu.png
  static/content/blog/how-to-build-a-simple-ivr-with-ruby-on-rails/numbers-menu-options.png
  static/content/blog/how-to-build-a-simple-ivr-with-ruby-on-rails/voice-menu-options.png
Labels: netlify-cms/pending_publish

#1010 Update Blog Post “building-a-slack-clone-using-vue-js-part-1-dr”
  content/blog/en/building-a-slack-clone-using-vue-js-part-1-dr.md
  static/content/blog/building-a-slack-clone-using-vue-js-–-part-1/basic-express-server-running.png
  static/content/blog/building-a-slack-clone-using-vue-js-–-part-1/basic-vue-client-running.png
  static/content/blog/building-a-slack-clone-using-vue-js-–-part-1/chat-client-working-beautifully.png
  static/content/blog/building-a-slack-clone-using-vue-js-–-part-1/chat-client-working.png
  static/content/blog/building-a-slack-clone-using-vue-js-–-part-1/chat-part-2-sneak-peek.png
  static/content/blog/building-a-slack-clone-using-vue-js-–-part-1/client-connecting-to-server.png
  static/content/blog/building-a-slack-clone-using-vue-js-–-part-1/client-loading-screen-with-spinner.png
  static/content/blog/building-a-slack-clone-using-vue-js-–-part-1/client-logging-in-to-service.png
  static/content/blog/building-a-slack-clone-using-vue-js-–-part-1/client-styles-after-tailwind-preflight.png
  static/content/blog/building-a-slack-clone-using-vue-js-–-part-1/error-caught-by-the-server.png
  static/content/blog/building-a-slack-clone-using-vue-js-–-part-1/server-and-client-running-concurrently.png
  static/content/blog/building-a-slack-clone-using-vue-js-–-part-1/server-status-api-endpoint.png
  static/content/blog/building-a-slack-clone-using-vue-js-–-part-1/user-session-api-endpoint.png
Labels: netlify-cms/pending_publish

#1020 Update Blog Post “javascript-hotline-with-opentok-and-nodejs-dr”
  content/blog/en/javascript-hotline-with-opentok-and-nodejs-dr.md
Labels: netlify-cms/pending_publish

#1021 Update Blog Post “discover-your-twitters-positivity-score-with-react-dr”
  content/blog/en/discover-your-twitters-positivity-score-with-react-dr.md
Labels: netlify-cms/pending_publish

#1023 Update Blog Post “nahrin-jalal-joins-the-nexmo-developer-education-team-dr”
  content/blog/en/nahrin-jalal-joins-the-nexmo-developer-education-team-dr.md
Labels: netlify-cms/pending_publish

#1022 Update Blog Post “announcing-nexmos-net-server-sdk-version-4-3-0-release-dr”
  content/blog/en/announcing-nexmos-net-server-sdk-version-4-3-0-release-dr.md
Labels: netlify-cms/pending_publish

#1019 Update Blog Post “daniela-joins-the-nexmo-developer-relations-team-dr”
  content/blog/en/daniela-joins-the-nexmo-developer-relations-team-dr.md
Labels: netlify-cms/pending_publish

#1027 Update Blog Post “introducing-custom-channel-in-conversations-dr”
  content/blog/en/introducing-custom-channel-in-conversations-dr.md
Labels: netlify-cms/pending_publish

#1029 Update Blog Post “how-to-build-a-voicemail-with-asp-net-core-and-nancyfx-dr”
  content/blog/en/how-to-build-a-voicemail-with-asp-net-core-and-nancyfx-dr.md
Labels: netlify-cms/pending_publish

#1024 Update Blog Post “nexmo-node-server-sdk-support-host-overriding-dr”
  content/blog/en/nexmo-node-server-sdk-support-host-overriding-dr.md
  static/content/blog/nexmo’s-node-js-server-sdk-added-support-for-host-overriding/curlhub.png
Labels: netlify-cms/pending_publish

#1028 Update Blog Post “kevin-joins-the-nexmo-developer-relations-team”
  content/blog/en/kevin-joins-the-nexmo-developer-relations-team.md
Labels: netlify-cms/pending_publish

#1025 Update Blog Post “using-github-repository-guidelines-to-enhance-developer-experience-dr”
  content/blog/en/using-github-repository-guidelines-to-enhance-developer-experience-dr.md
Labels: netlify-cms/pending_publish

#1030 Update Blog Post “stream-audio-node-red-dr”
  content/blog/en/stream-audio-node-red-dr.md
  static/content/blog/how-to-stream-audio-into-a-call-with-node-red/buy-number-nexmo-dashboard.png
  static/content/blog/how-to-stream-audio-into-a-call-with-node-red/create-voice-app-example-1.png
  static/content/blog/how-to-stream-audio-into-a-call-with-node-red/edit-createcall-1.png
  static/content/blog/how-to-stream-audio-into-a-call-with-node-red/event-webhook-1.png
  static/content/blog/how-to-stream-audio-into-a-call-with-node-red/install-nexmo-nodered.png
  static/content/blog/how-to-stream-audio-into-a-call-with-node-red/link-number-voiceapp-1.png
  static/content/blog/how-to-stream-audio-into-a-call-with-node-red/ngrok-manage-palette.png
  static/content/blog/how-to-stream-audio-into-a-call-with-node-red/ngrok-node-properties-1.png
  static/content/blog/how-to-stream-audio-into-a-call-with-node-red/ngrok-nodered-1.png
  static/content/blog/how-to-stream-audio-into-a-call-with-node-red/serve-up-audio-nodered-1.png
  static/content/blog/how-to-stream-audio-into-a-call-with-node-red/stream-msg-ncco-1.png
  static/content/blog/how-to-stream-audio-into-a-call-with-node-red/stream-ncco-answer-url-1-1-.png
  static/content/blog/how-to-stream-audio-into-a-call-with-node-red/stream-outbound-debug-1.png
Labels: netlify-cms/pending_publish

#1031 Update Blog Post “dockerize-python-queue-manager-project-for-easy-deployment-dr”
  content/blog/en/dockerize-python-queue-manager-project-for-easy-deployment-dr.md
  static/content/blog/dockerize-python-queue-manager-project-for-easy-deployment/heroku-config-vars.png
Labels: netlify-cms/pending_publish

#1033 Update Blog Post “stream-audio-node-red-dr”
  content/blog/en/stream-audio-node-red-dr.md
Labels: netlify-cms/pending_publish

#1034 Update Blog Post “how-to-build-a-voicemail-with-asp-net-core-and-nancyfx-dr”
  content/blog/en/how-to-build-a-voicemail-with-asp-net-core-and-nancyfx-dr.md
Labels: netlify-cms/pending_publish

#1032 Update Blog Post “adaptive-library-logging-with-microsoft-extensions-logging-dr”
  content/blog/en/adaptive-library-logging-with-microsoft-extensions-logging-dr.md
Labels: netlify-cms/pending_publish

#1036 Update Blog Post “how-to-send-sms-messages-with-elixir-dr”
  content/blog/en/how-to-send-sms-messages-with-elixir-dr.md
  static/content/blog/how-to-send-sms-messages-with-elixir/elixir-api-credentials.png
  static/content/blog/how-to-send-sms-messages-with-elixir/elixir-buy-number-button.png
  static/content/blog/how-to-send-sms-messages-with-elixir/elixir-buy-numbers-search.png
  static/content/blog/how-to-send-sms-messages-with-elixir/elixir-buy-numbers-sidebar.png
Labels: netlify-cms/pending_publish

#1035 Update Blog Post “nick-iati-joins-the-nexmo-developer-relations-team-dr”
  content/blog/en/nick-iati-joins-the-nexmo-developer-relations-team-dr.md
Labels: netlify-cms/pending_publish

#1038 Create Blog Post “startup-spotlight-lets-meet-tucuvi”
  content/blog/en/startup-spotlight-lets-meet-tucuvi.md
  static/content/blog/startup-spotlight-lets-meet-tucuvi/startups_tucuvi_1200x600.png
Labels: netlify-cms/pending_publish

#1039 Update Blog Post “startup-spotlight-lets-meet-tucuvi”
  content/blog/en/startup-spotlight-lets-meet-tucuvi.md
Labels: netlify-cms/pending_publish

#1046 Update Blog Post “stream-audio-node-red-dr”
  static/content/blog/how-to-stream-audio-into-a-call-with-node-red/stream-ncco-answer-url-1.png
Labels: netlify-cms/pending_publish

#1037 Update Blog Post “aws-transcribe-with-nexmo-voice-using-php-dr”
  content/blog/en/aws-transcribe-with-nexmo-voice-using-php-dr.md
  static/content/blog/aws-transcribe-with-nexmo-voice-using-php/aws-authentication_keys.png
  static/content/blog/aws-transcribe-with-nexmo-voice-using-php/aws-create_application.png
  static/content/blog/aws-transcribe-with-nexmo-voice-using-php/aws-link_the_app.png
  static/content/blog/aws-transcribe-with-nexmo-voice-using-php/aws-nexmo_dashboard.png
  static/content/blog/aws-transcribe-with-nexmo-voice-using-php/aws-ngrok_output.png
  static/content/blog/aws-transcribe-with-nexmo-voice-using-php/aws-select_iam_management.png
  static/content/blog/aws-transcribe-with-nexmo-voice-using-php/aws-voice_urls.png
  static/content/blog/aws-transcribe-with-nexmo-voice-using-php/aws_new_iam_user.png
Labels: netlify-cms/pending_publish

#1040 Update Blog Post “make-calls-with-a-custom-call-button-in-your-ios-app-dr”
  content/blog/en/make-calls-with-a-custom-call-button-in-your-ios-app-dr.md
  static/content/blog/make-calls-with-a-custom-call-button-in-your-ios-app/8f6llac.png
  static/content/blog/make-calls-with-a-custom-call-button-in-your-ios-app/a0usjgx.png
  static/content/blog/make-calls-with-a-custom-call-button-in-your-ios-app/eyw8ryb.png
  static/content/blog/make-calls-with-a-custom-call-button-in-your-ios-app/n2h46i2.png
Labels: netlify-cms/pending_publish

#1041 Update Blog Post “video-with-text-chat”
  content/blog/en/video-with-text-chat.md
  static/content/blog/add-texting-functionality-to-a-video-chat-with-vonage-video-api/0d17c722-4359-4e32-b770-32fcae5a3653_button.png
  static/content/blog/add-texting-functionality-to-a-video-chat-with-vonage-video-api/0d17c722-4359-4e32-b770-32fcae5a3653_chat-window.png
  static/content/blog/add-texting-functionality-to-a-video-chat-with-vonage-video-api/0d17c722-4359-4e32-b770-32fcae5a3653_final.jpg
  static/content/blog/add-texting-functionality-to-a-video-chat-with-vonage-video-api/0d17c722-4359-4e32-b770-32fcae5a3653_glitch-01.jpg
  static/content/blog/add-texting-functionality-to-a-video-chat-with-vonage-video-api/0d17c722-4359-4e32-b770-32fcae5a3653_glitch-02.png
  static/content/blog/add-texting-functionality-to-a-video-chat-with-vonage-video-api/0d17c722-4359-4e32-b770-32fcae5a3653_pouchdb.jpg
  static/content/blog/add-texting-functionality-to-a-video-chat-with-vonage-video-api/0d17c722-4359-4e32-b770-32fcae5a3653_stream-name.jpg
Labels: netlify-cms/pending_publish

#1043 Update Blog Post “send-a-viber-message-with-node-dr”
  content/blog/en/send-a-viber-message-with-node-dr.md
Labels: netlify-cms/pending_publish

#1048 Update Blog Post “dial-ynab-dr”
  content/blog/en/dial-ynab-dr.md
  static/content/blog/keep-track-of-your-budget-with-dial-ynab/dial-ynab-ngrok.png
  static/content/blog/keep-track-of-your-budget-with-dial-ynab/dial-ynab-sequence-diagram.png
Labels: netlify-cms/pending_publish

#1047 Update Blog Post “voice-classification-nlp-google-cloud-dr”
  content/blog/en/voice-classification-nlp-google-cloud-dr.md
  static/content/blog/automatically-classify-your-call-recordings-using-natural-language-processing/codesnippet01.png
Labels: netlify-cms/pending_publish

#1049 Update Blog Post “receiving-sms-delivery-receipts-with-java-and-spark-dr”
  content/blog/en/receiving-sms-delivery-receipts-with-java-and-spark-dr.md
  static/content/blog/receiving-sms-delivery-receipts-with-java-and-spark/dlr-settings.png
  static/content/blog/receiving-sms-delivery-receipts-with-java-and-spark/ngrok-urls.png
Labels: netlify-cms/pending_publish

#1051 Update Blog Post “play-an-audio-file-into-a-voice-call-with-java-and-spark-dr”
  content/blog/en/play-an-audio-file-into-a-voice-call-with-java-and-spark-dr.md
  static/content/blog/play-an-audio-file-into-a-voice-call-with-java-and-spark/ngrok-urls.png
Labels: netlify-cms/pending_publish

#1050 Update Blog Post “checking-the-tube-status-with-nexmo-and-tfl-apis-dr”
  content/blog/en/checking-the-tube-status-with-nexmo-and-tfl-apis-dr.md
  static/content/blog/checking-the-london-tube-status-with-nexmo’s-sms-api/demo.gif
  static/content/blog/checking-the-london-tube-status-with-nexmo’s-sms-api/herokudashboard.png
  static/content/blog/checking-the-london-tube-status-with-nexmo’s-sms-api/mock.png
  static/content/blog/checking-the-london-tube-status-with-nexmo’s-sms-api/sms.png
  static/content/blog/checking-the-london-tube-status-with-nexmo’s-sms-api/workflow.png
Labels: netlify-cms/pending_publish

#1052 Update Blog Post “voice-chat-with-vue-and-express-dr”
  content/blog/en/voice-chat-with-vue-and-express-dr.md
Labels: netlify-cms/pending_publish

#1053 Update Blog Post “checking-the-tube-status-with-nexmo-and-tfl-apis-dr”
  content/blog/en/checking-the-tube-status-with-nexmo-and-tfl-apis-dr.md
Labels: netlify-cms/pending_publish

#1054 Update Blog Post “play-an-audio-file-into-a-voice-call-with-java-and-spark-dr”
  content/blog/en/play-an-audio-file-into-a-voice-call-with-java-and-spark-dr.md
Labels: netlify-cms/pending_publish
