Repository Nexmo/deved-platform, pull requests merged in 2021-02, with the labels that each got.

#653 Create Blog Post “build-a-text-to-speech-application-with-hanami”
  content/blog/en/build-a-text-to-speech-application-with-hanami.md
  static/content/blog/build-a-text-to-speech-application-with-hanami/ruby-hanami_voice_1200x627.jpg
Labels: netlify-cms/pending_publish

#659 Create Authors “dillion-megida”
  content/authors/dillion-megida.json
  static/content/images/img_3318.jpeg
Labels: netlify-cms/pending_publish

#660 Update Blog Post “how-to-make-phone-calls-with-swiftui”
  static/content/blog/how-to-make-phone-calls-with-swiftui/call.gif
Labels: netlify-cms/pending_publish

#657 Create Blog Post “building-github-actions-with-the-vonage-messages-api”
  content/blog/en/building-github-actions-with-the-vonage-messages-api.md
  static/content/blog/building-github-actions-with-the-vonage-messages-api/1.-vonage-developer-dashboard-for-setting-up-a-sandbox.png
  static/content/blog/building-github-actions-with-the-vonage-messages-api/2.-whatsapp-app-after-clicking-generated-link-gotten-after-adding-whatsapp-channel-to-sandbox.png
  static/content/blog/building-github-actions-with-the-vonage-messages-api/3.-example-code-for-using-the-whatsapp-api.png
  static/content/blog/building-github-actions-with-the-vonage-messages-api/4.-result-gotten-after-executing-test-script.png
  static/content/blog/building-github-actions-with-the-vonage-messages-api/5.-error-from-running-the-workflow.png
  static/content/blog/building-github-actions-with-the-vonage-messages-api/6.-screenshot-of-whatsapp-message-sent-to-a-whitelisted-number.jpg
  static/content/blog/building-github-actions-with-the-vonage-messages-api/github-whatsapp-1200x600.png
Labels: needs-review, netlify-cms/pending_publish

#665 Update Blog Post “building-github-actions-with-the-vonage-messages-api”
  content/blog/en/building-github-actions-with-the-vonage-messages-api.md
Labels: netlify-cms/pending_publish

#667 Update Blog Post “building-github-actions-with-the-vonage-messages-api”
  content/blog/en/building-github-actions-with-the-vonage-messages-api.md
  static/content/blog/building-github-actions-with-the-vonage-messages-api/1.-setup-sandbox.png
  static/content/blog/building-github-actions-with-the-vonage-messages-api/2.-whatsapp-app-after-clicking-generated-link-gotten-after-adding-whatsapp-channel-to-sandbox.png
  static/content/blog/building-github-actions-with-the-vonage-messages-api/3.-example-code-for-using-the-api.png
Labels: netlify-cms/pending_publish

#634 feat(spotlight): add developer spotlight landing page and form
  components/Footer.vue
  deved-platform.code-workspace
  pages/spotlight/index.vue
  pages/spotlight/success.vue
  tailwind.config.js
Labels: needs-review

#677 Update Blog Post “build-a-text-to-speech-application-with-hanami”
  content/blog/en/build-a-text-to-speech-application-with-hanami.md
Labels: netlify-cms/pending_publish

#672 Create Blog Post “add-sip-calls-to-webrtc-video-sessions”
  content/blog/en/add-sip-calls-to-webrtc-video-sessions.md
  static/content/blog/add-sip-calls-to-webrtc-video-sessions/callmemaybe_1200x627.png
  static/content/blog/add-sip-calls-to-webrtc-video-sessions/ot-project-created.png
Labels: netlify-cms/pending_publish

#680 Update Authors “dillion-megida”
  content/authors/dillion-megida.json
Labels: netlify-cms/pending_publish

#683 Create DevTV Shows “week-init”
  content/shows/week-init.json
  static/content/shows/week-init/week.init_twitter_gt26mi.png
Labels: netlify-cms/draft

#687 Create DevTV Episodes “2021-02-10-conversation-apis”
  content/shows/episodes/2021-02-10-conversation-apis.json
  static/content/shows/episodes/conversation-apis/week.init_twitter_gt26mi.png
Labels: netlify-cms/draft

#671 Create Blog Post “build-an-interactive-voice-response-with-go”
  content/blog/en/build-an-interactive-voice-response-with-go.md
  static/content/blog/build-an-interactive-voice-response-with-go/go_ivr_1200x627.png
Labels: needs-review, netlify-cms/pending_publish

#693 Create DevTV Shows “lauren-learns-things”
  CHANGELOG.md
  content/authors/dillion-megida.json
  content/blog/en/add-sip-calls-to-webrtc-video-sessions.md
  content/blog/en/build-a-text-to-speech-application-with-hanami.md
  content/blog/en/build-an-interactive-voice-response-with-go.md
  content/shows/episodes/2021-02-10-conversation-apis.json
  content/shows/lauren-learns-things.json
  content/shows/week-init.json
  package-lock.json
  package.json
  static/content/blog/add-sip-calls-to-webrtc-video-sessions/callmemaybe_1200x627.png
  static/content/blog/add-sip-calls-to-webrtc-video-sessions/ot-project-created.png
  static/content/blog/build-an-interactive-voice-response-with-go/go_ivr_1200x627.png
  static/content/shows/episodes/conversation-apis/week.init_twitter_gt26mi.png
  static/content/shows/lauren-learns-things/twitch-show-social-graphics-2-.png
  static/content/shows/week-init/week.init_twitter_gt26mi.png
Labels: netlify-cms/draft

#699 Create DevTV Episodes “2021-02-12-how-to-build-a-2fa-server-with-kotlin-and-ktor”
  content/shows/episodes/2021-02-12-how-to-build-a-2fa-server-with-kotlin-and-ktor.json
Labels: netlify-cms/pending_publish

#703 Create DevTV Shows “vonage-gems-1”
  content/shows/vonage-gems-1.json
  static/content/shows/vonage-gems/vonage_gems.png
Labels: netlify-cms/pending_publish

#674 Create Blog Post “using-web-components-in-an-angular-application-joyful-fun”
  content/blog/en/using-web-components-in-an-angular-application-joyful-fun.md
  static/content/blog/using-web-components-in-an-angular-application-joyful-fun/custom-elements-everywhere-angular.jpg
  static/content/blog/using-web-components-in-an-angular-application-joyful-fun/custom_elements_schema-error.jpg
  static/content/blog/using-web-components-in-an-angular-application-joyful-fun/web-components_angular_1200x600.png
Labels: needs-review, netlify-cms/pending_publish

#691 Create Blog Post “announcing-vonage-ruby-sdk-version-7-3-0”
  content/blog/en/announcing-vonage-ruby-sdk-version-7-3-0.md
  static/content/blog/announcing-vonage-ruby-sdk-version-7-3-0/blog_ruby-sdk-update_1200x600.png
Labels: needs-review, netlify-cms/pending_publish

#709 Update Blog Post “announcing-vonage-ruby-sdk-version-7-3-0”
  content/blog/en/announcing-vonage-ruby-sdk-version-7-3-0.md
Labels: netlify-cms/pending_publish

#710 Create DevTV Episodes “2021-02-17-guest-myrsini-koukiasa”
  content/shows/episodes/2021-02-17-guest-myrsini-koukiasa.json
  static/content/shows/episodes/guest-myrsini-koukiasa/twitch-show-social-graphics-47-.png
Labels: netlify-cms/draft

#711 Update DevTV Episodes “2021-02-17-guest-myrsini-koukiasa”
  content/shows/episodes/2021-02-17-guest-myrsini-koukiasa.json
Labels: netlify-cms/pending_publish

#712 Create DevTV Episodes “2021-02-17-conversation-apis”
  content/shows/episodes/2021-02-17-conversation-apis.json
Labels: netlify-cms/pending_publish

#713 Update DevTV Episodes “2021-02-17-conversation-apis”
  content/shows/episodes/2021-02-17-conversation-apis.json
Labels: netlify-cms/pending_publish

#714 Update DevTV Episodes “2021-02-17-conversation-apis”
  content/shows/episodes/2021-02-17-conversation-apis.json
Labels: netlify-cms/pending_publish

#715 Update DevTV Episodes “2021-02-17-conversation-apis”
  content/shows/episodes/2021-02-17-conversation-apis.json
Labels: netlify-cms/pending_publish

#716 Create DevTV Episodes “2021-02-17-conversation-apis-nodejs”
  content/shows/episodes/2021-02-17-conversation-apis-nodejs.json
Labels: netlify-cms/pending_publish

#717 Create DevTV Episodes “2021-02-17-topic-to-be-determined”
  content/shows/episodes/2021-02-17-topic-to-be-determined.json
Labels: netlify-cms/pending_publish

#718 Create DevTV Episodes “2021-02-17-topic-to-be-determined-1”
  content/shows/episodes/2021-02-17-topic-to-be-determined-1.json
Labels: netlify-cms/pending_publish

#719 Create DevTV Episodes “2021-02-17-conversation-apis-nodejs-1”
  content/shows/episodes/2021-02-17-conversation-apis-nodejs-1.json
Labels: netlify-cms/pending_publish

#721 Create DevTV Episodes “2021-02-17-international-womens-day-panel-1”
  content/shows/episodes/2021-02-17-international-womens-day-panel-1.json
Labels: netlify-cms/pending_publish

#722 Create DevTV Episodes “2021-02-17-meet-the-vonage-rubyists-fabian-rodriguez”
  content/shows/episodes/2021-02-17-meet-the-vonage-rubyists-fabian-rodriguez.json
  static/content/shows/episodes/meet-the-vonage-rubyists-fabian-rodriguez/twitch-show-social-graphics-51-.png
Labels: netlify-cms/pending_publish

#723 Create DevTV Episodes “2021-02-17-to-be-determined”
  content/shows/episodes/2021-02-17-to-be-determined.json
Labels: netlify-cms/pending_publish

#724 Create DevTV Episodes “2021-02-17-guest-michael-heap”
  content/shows/episodes/2021-02-17-guest-michael-heap.json
  static/content/shows/episodes/guest-michael-heap/twitch-show-social-graphics-48-.png
Labels: netlify-cms/pending_publish

#720 Create DevTV Episodes “2021-02-17-international-womens-day-panel”
  content/shows/episodes/2021-02-17-international-womens-day-panel.json
Labels: netlify-cms/pending_publish

#682 Create Blog Post “technical-guide-for-us-short-code-api-deprecation”
  content/blog/en/technical-guide-for-us-short-code-api-deprecation.md
Labels: needs-review, netlify-cms/pending_review

#681 Update Blog Post “building-github-actions-with-the-vonage-messages-api”
  content/blog/en/building-github-actions-with-the-vonage-messages-api.md
Labels: needs-review, netlify-cms/pending_publish

#725 Create Blog Post “technical-guide-for-us-short-code-api-deprecation-1”
  content/blog/en/technical-guide-for-us-short-code-api-deprecation-1.md
  static/content/blog/technical-guide-for-us-short-code-api-deprecation/shortcode_deprecation_1200x600.png
Labels: netlify-cms/pending_publish

#726 Update Blog Post “technical-guide-for-us-short-code-api-deprecation-1”
  content/blog/en/technical-guide-for-us-short-code-api-deprecation-1.md
Labels: netlify-cms/pending_publish

#727 Update Blog Post “technical-guide-for-us-short-code-api-deprecation-1”
  content/blog/en/technical-guide-for-us-short-code-api-deprecation-1.md
Labels: netlify-cms/pending_publish

#728 Create DevTV Episodes “2021-02-21-topic-to-be-determined”
  content/shows/episodes/2021-02-21-topic-to-be-determined.json
Labels: netlify-cms/pending_publish

#740 Create Authors “isabel-hildebrand”
  content/authors/isabel-hildebrand.json
  static/content/images/photo_2020-11-19-9.05.55-pm.jpeg
Labels: netlify-cms/pending_publish

#619 Create Blog Post “vonage-developer-relations-in-2020”
  content/blog/en/vonage-developer-relations-in-2020.md
  static/content/blog/vonage-developer-relations-in-2020/2020_recap2_1200x600.png
  static/content/blog/vonage-developer-relations-in-2020/vonage-2020infographic-v7-external.png
Labels: needs-review, netlify-cms/pending_publish

#741 Update Authors “martyn”
  content/authors/martyn.json
Labels: needs-review, netlify-cms/pending_publish

#742 Create Blog Post “introducing-vonage-for-startups”
  content/blog/en/introducing-vonage-for-startups.md
  static/content/blog/introducing-vonage-for-startups/vonageforstartups_1200x600.png
Labels: needs-review, netlify-cms/pending_publish

#746 Update Blog Post “introducing-vonage-for-startups”
  content/blog/en/introducing-vonage-for-startups.md
Labels: netlify-cms/pending_publish

#748 Update Blog Post “introducing-vonage-for-startups”
  content/blog/en/introducing-vonage-for-startups.md
Labels: netlify-cms/pending_publish

#752 Create Authors “temiloluwa-ojo”
  content/authors/temiloluwa-ojo.json
  static/content/images/img_20201031_044526.jpg
Labels: netlify-cms/pending_publish

#753 Update Blog Post “technical-guide-for-us-short-code-api-deprecation-1”
  content/blog/en/technical-guide-for-us-short-code-api-deprecation-1.md
Labels: netlify-cms/pending_publish

#754 Create Blog Post “building-a-realtime-graphql-chat-application-with-sms-notifications”
  content/blog/en/building-a-realtime-graphql-chat-application-with-sms-notifications.md
  static/content/blog/building-a-realtime-graphql-chat-application-with-sms-notifications/nextjs_prisma-2_graphql_sms-1200x600.png
Labels: netlify-cms/pending_publish

#755 Update Blog Post “building-a-realtime-graphql-chat-application-with-sms-notifications”
  content/blog/en/building-a-realtime-graphql-chat-application-with-sms-notifications.md
Labels: netlify-cms/pending_publish

#758 Update DevTV Episodes “2021-02-17-topic-to-be-determined-1”
  content/shows/episodes/2021-02-17-topic-to-be-determined-1.json
Labels: netlify-cms/pending_publish

#759 Update Blog Post “building-a-realtime-graphql-chat-application-with-sms-notifications”
  content/blog/en/building-a-realtime-graphql-chat-application-with-sms-notifications.md
Labels: netlify-cms/pending_publish
