Repository Nexmo/deved-platform, pull requests merged in 2021-06, with the labels that each got.

#1401 Create Blog Post “deploying-pythonanywhere-with-the-messages-api”
  content/blog/en/deploying-pythonanywhere-with-the-messages-api.md
  static/content/blog/deploying-pythonanywhere-with-the-messages-api/console.png
  static/content/blog/deploying-pythonanywhere-with-the-messages-api/final_li.jpeg
  static/content/blog/deploying-pythonanywhere-with-the-messages-api/helloworld.png
  static/content/blog/deploying-pythonanywhere-with-the-messages-api/messages_pythonanywhere_1200x600.png
  static/content/blog/deploying-pythonanywhere-with-the-messages-api/sandbox.png
  static/content/blog/deploying-pythonanywhere-with-the-messages-api/sandbox_2.png
  static/content/blog/deploying-pythonanywhere-with-the-messages-api/url_li_-3-.jpeg
  static/content/blog/deploying-pythonanywhere-with-the-messages-api/web_app.png
  static/content/blog/deploying-pythonanywhere-with-the-messages-api/web_app2.png
  static/content/blog/deploying-pythonanywhere-with-the-messages-api/whatsapp.png
  static/content/blog/deploying-pythonanywhere-with-the-messages-api/wsgi_li.jpeg
Labels: needs-review, netlify-cms/pending_publish

#1442 Update Blog Post “handling-voip-push-notifications-with-callkit”
  content/blog/en/handling-voip-push-notifications-with-callkit.md
Labels: netlify-cms/pending_publish

#1443 Update Blog Post “best-practices-to-get-started-with-the-vonage-video-api”
  content/blog/en/best-practices-to-get-started-with-the-vonage-video-api.md
Labels: netlify-cms/pending_publish

#1447 Update Blog Post “building-voice-alerts-broadcast-system-using-ruby-nexmo-text-speech-api-dr”
  content/blog/en/building-voice-alerts-broadcast-system-using-ruby-nexmo-text-speech-api-dr.md
Labels: netlify-cms/pending_publish

#1430 Create Blog Post “using-terraform-for-database-management”
  content/blog/en/using-terraform-for-database-management.md
  static/content/blog/using-terraform-for-database-management/db_pushplans-overview.png
  static/content/blog/using-terraform-for-database-management/terraform_database-management_1200x600.png
Labels: needs-review, netlify-cms/pending_publish

#1449 Create Authors “avadhut-phatarpekar”
  content/authors/avadhut-phatarpekar.json
  static/content/images/untitled.png
Labels: netlify-cms/pending_publish

#1448 Update Blog Post “using-terraform-for-database-management”
  content/blog/en/using-terraform-for-database-management.md
Labels: netlify-cms/pending_publish

#1446 Create Blog Post “startup-spotlight-series-lets-meet-agserver”
  content/blog/en/startup-spotlight-series-lets-meet-agserver.md
  static/content/blog/startup-spotlight-series-lets-meet-agserver/startups_agserver_1200x600-1-.png
Labels: netlify-cms/pending_publish

#1451 Update Blog Post “startup-spotlight-series-lets-meet-agserver”
  content/blog/en/startup-spotlight-series-lets-meet-agserver.md
Labels: netlify-cms/pending_publish

#1111 Cross reference Flutter Articles
  content/blog/en/make-app-to-phone-call-using-android-and-flutter.md
  content/blog/en/make-app-to-phone-call-using-ios-and-flutter.md
Labels: needs-review

#1438 Update Blog Post “send-and-receive-sms-messages-with-firebase-functions-dr”
  content/blog/en/send-and-receive-sms-messages-with-firebase-functions-dr.md
  static/content/blog/send-and-receive-sms-messages-with-firebase-functions/analytics.png
  static/content/blog/send-and-receive-sms-messages-with-firebase-functions/console.png
  static/content/blog/send-and-receive-sms-messages-with-firebase-functions/modifyplan.png
  static/content/blog/send-and-receive-sms-messages-with-firebase-functions/realtimedatabase.png
  static/content/blog/send-and-receive-sms-messages-with-firebase-functions/update-location.png
Labels: needs-review, netlify-cms/pending_publish

#1458 Create Blog Post “vonage-and-freshworks-join-forces-to-support-exceptional-founders”
  content/blog/en/vonage-and-freshworks-join-forces-to-support-exceptional-founders.md
  static/content/blog/vonage-and-freshworks-join-forces-to-support-exceptional-founders/vonage_freshworks-startups_1200x600.png
Labels: netlify-cms/pending_publish

#1469 Create Authors “nick-anderson-1”
  content/authors/nick-anderson-1.json
  static/content/images/nickpic.jpg
Labels: netlify-cms/pending_publish

#1472 Create Authors “tonya-sims-1”
  content/authors/tonya-sims-1.json
  static/content/images/me.png
Labels: netlify-cms/pending_publish

#1450 Create Blog Post “a-better-way-of-creating-android-views-with-jetpackcompose”
  content/blog/en/a-better-way-of-creating-android-views-with-jetpackcompose.md
  static/content/blog/a-better-way-of-creating-android-views-with-jetpackcompose/andriod_jetpack-compose_1200x600.png
  static/content/blog/a-better-way-of-creating-android-views-with-jetpackcompose/preview1.png
  static/content/blog/a-better-way-of-creating-android-views-with-jetpackcompose/preview2.png
  static/content/blog/a-better-way-of-creating-android-views-with-jetpackcompose/preview3.png
Labels: needs-review, netlify-cms/pending_publish

#1477 Create Blog Post “startup-spotlight-series-lets-meet-plato-immo”
  content/blog/en/startup-spotlight-series-lets-meet-plato-immo.md
  static/content/blog/startup-spotlight-lets-meet-plato-immo/startups_plato_1200x600.png
  static/content/blog/startup-spotlight-series-lets-meet-plato-immo/startups_plato_1200x600.png
Labels: netlify-cms/pending_publish

#1481 Update Blog Post “how-to-make-video-calls-with-swiftui”
  content/blog/en/how-to-make-video-calls-with-swiftui.md
Labels: netlify-cms/pending_publish

#1482 Update Blog Post “startup-spotlight-lets-meet-commons”
  content/blog/en/startup-spotlight-lets-meet-commons.md
Labels: netlify-cms/pending_publish

#1463 Create Blog Post “voice-security-improvements”
  content/blog/en/voice-security-improvements.md
  static/content/blog/voice-security-improvements/voice-security_1200x600.png
Labels: needs-review, netlify-cms/pending_publish

#1484 Create Authors “simon-jones”
  content/authors/simon-jones.json
  static/content/images/screenshot_20210617-112327_gallery.jpg
Labels: netlify-cms/pending_publish

#1483 Update Blog Post “best-practices-to-get-started-with-the-vonage-video-api”
  content/blog/en/best-practices-to-get-started-with-the-vonage-video-api.md
Labels: netlify-cms/pending_publish

#1491 Update Blog Post “startup-spotlight-series-lets-meet-plato-immo”
  content/blog/en/startup-spotlight-series-lets-meet-plato-immo.md
Labels: netlify-cms/pending_publish

#1492 Update Blog Post “vonage-and-freshworks-join-forces-to-support-exceptional-founders”
  content/blog/en/vonage-and-freshworks-join-forces-to-support-exceptional-founders.md
Labels: netlify-cms/pending_publish

#1493 Update Blog Post “startup-spotlight-series-lets-meet-agserver”
  content/blog/en/startup-spotlight-series-lets-meet-agserver.md
Labels: netlify-cms/pending_publish

#1494 Update Blog Post “startup-spotlight-lets-meet-commons”
  content/blog/en/startup-spotlight-lets-meet-commons.md
Labels: netlify-cms/pending_publish

#1495 Update Blog Post “startup-community-partner-build-up-labs”
  content/blog/en/startup-community-partner-build-up-labs.md
Labels: netlify-cms/pending_publish

#1496 Update Blog Post “startup-community-partner-aurelia-ventures”
  content/blog/en/startup-community-partner-aurelia-ventures.md
Labels: netlify-cms/pending_publish

#1497 Update Blog Post “startup-spotlight-lets-meet-tucuvi”
  content/blog/en/startup-spotlight-lets-meet-tucuvi.md
Labels: netlify-cms/pending_publish

#1498 Update Blog Post “startup-community-partner-dms-accelerator”
  content/blog/en/startup-community-partner-dms-accelerator.md
Labels: netlify-cms/pending_publish

#1499 Update Blog Post “startup-spotlight-series-billseye”
  content/blog/en/startup-spotlight-series-billseye.md
Labels: netlify-cms/pending_publish

#1501 Update Blog Post “introducing-vonage-for-startups”
  content/blog/en/introducing-vonage-for-startups.md
Labels: netlify-cms/pending_publish

#1473 Create Blog Post “tonya-sims-joins-the-vonage-developer-relations-team”
  content/blog/en/tonya-sims-joins-the-vonage-developer-relations-team.md
  static/content/blog/tonya-sims-joins-the-vonage-developer-relations-team/me.png
  static/content/blog/tonya-sims-joins-the-vonage-developer-relations-team/tonya-sims.png
Labels: needs-review, netlify-cms/pending_publish

#1500 Update Blog Post “why-should-your-startup-use-communications-apis”
  content/blog/en/why-should-your-startup-use-communications-apis.md
Labels: netlify-cms/pending_publish

#1507 Update Authors “tonya-sims-1”
  content/authors/tonya-sims-1.json
Labels: netlify-cms/pending_publish

#1508 Update Authors “tonya-sims-1”
  content/authors/tonya-sims-1.json
  static/content/images/tonya.png
Labels: netlify-cms/pending_publish

#1457 Create Blog Post “build-a-birthday-congratulations-time-capsule-with-go”
  content/blog/en/build-a-birthday-congratulations-time-capsule-with-go.md
  static/content/blog/build-a-birthday-congratulations-time-capsule-with-go/go_birthday_voiceapi_1200x600.png
Labels: needs-review, netlify-cms/pending_publish

#1511 Update Blog Post “tonya-sims-joins-the-vonage-developer-relations-team”
  content/blog/en/tonya-sims-joins-the-vonage-developer-relations-team.md
Labels: netlify-cms/pending_publish

#1486 Create Blog Post “startup-spotlight-series-lets-meet-oeto”
  content/blog/en/startup-spotlight-series-lets-meet-oeto.md
  static/content/blog/startup-spotlight-lets-meet-oeto/startups_oeto_1200x600.png
  static/content/blog/startup-spotlight-series-lets-meet-oeto/startups_oeto_1200x600.png
Labels: needs-review, netlify-cms/pending_publish

#1512 Update Blog Post “startup-spotlight-series-lets-meet-plato-immo”
  content/blog/en/startup-spotlight-series-lets-meet-plato-immo.md
Labels: netlify-cms/pending_publish

#1456 Create Blog Post “my-first-month-in-devrel”
  content/blog/en/my-first-month-in-devrel.md
  static/content/blog/my-first-month-in-devrel/first-month_1200x600.png
  static/content/blog/my-first-month-in-devrel/pxl_20210610_121009759.jpg
Labels: needs-review, netlify-cms/pending_publish

#1468 Create Authors “nick-anderson”
  content/authors/nick-anderson.json
Labels: needs-review, netlify-cms/pending_publish

#1476 Create Blog Post “nick-anderson-has-joined-the-technical-writer-team”
  content/blog/en/nick-anderson-has-joined-the-technical-writer-team.md
  static/content/blog/nick-anderson-has-joined-the-technical-writer-team/305bc94.jpg
  static/content/blog/nick-anderson-has-joined-the-technical-writer-team/nickcwa_bio.jpg
  static/content/blog/nick-anderson-joins-the-vonage-technical-writing-team/nick-anderson.png
Labels: needs-review, netlify-cms/pending_publish

#1516 Update Blog Post “create-websocket-server-spring-boot-dr”
  content/blog/en/create-websocket-server-spring-boot-dr.md
  static/content/blog/creating-a-websocket-server-with-spring-boot/screenshot-2021-06-24-at-22.33.33.png
  static/content/blog/creating-a-websocket-server-with-spring-boot/screenshot-2021-06-24-at-22.36.00.png
  static/content/blog/creating-a-websocket-server-with-spring-boot/screenshot-2021-06-24-at-22.52.15.png
Labels: netlify-cms/pending_publish

#1509 Update Blog Post “handling-voip-push-notifications-with-callkit”
  content/blog/en/handling-voip-push-notifications-with-callkit.md
Labels: needs-review, netlify-cms/pending_publish

#1502 Create Blog Post “the-functions-that-arent-pure”
  content/blog/en/the-functions-that-arent-pure.md
  static/content/blog/the-functions-that-arent-pure/functional-programing_1200x600.png
Labels: needs-review, netlify-cms/pending_publish

#1521 Update Blog Post “a-better-way-of-creating-android-views-with-jetpackcompose”
  content/blog/en/a-better-way-of-creating-android-views-with-jetpackcompose.md
Labels: netlify-cms/pending_publish

#1522 Create Blog Post “startup-spotlight-series-lets-meet-speedbird-aero”
  content/blog/en/startup-spotlight-series-lets-meet-speedbird-aero.md
  static/content/blog/startup-spotlight-series-lets-meet-speedbird-aero/startups_speedbird_1200x600.png
Labels: netlify-cms/pending_publish

#1523 Update Blog Post “startup-spotlight-series-lets-meet-speedbird-aero”
  content/blog/en/startup-spotlight-series-lets-meet-speedbird-aero.md
Labels: netlify-cms/pending_publish

#1519 Add "Last updated on MMM D, YYYY" for blog posts
  pages/blog/_year/_month/_day/_slug.vue
Labels: enhancement
